{
 "title": "/Mesos-Allocator-Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "metrics(mesos_allocator_mesos_allocation_run_ms_)"
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time spent in allocation algorithm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_ms_[[percentile]]{state=\"leader\"}",
     "legendFormat": "$percentile"
    }
   ]
  },
  {
   "title": "Allocation batch latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_latency_ms_[[percentile]]{state=\"leader\"}",
     "legendFormat": "$percentile"
    }
   ]
  },
  {
   "title": "# of allocation runs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_runs{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_event_queue_dispatches{state=\"leader\"}",
     "legendFormat": "Dispatches"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPUs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_cpus_total{state=\"leader\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_mesos_resources_cpus_offered_or_allocated{state=\"leader\"}",
     "legendFormat": "Offered and allocated"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_mem_total{state=\"leader\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_mesos_resources_mem_offered_or_allocated{state=\"leader\"}",
     "legendFormat": "Offered and allocated"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_disk_total{state=\"leader\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "mesos_allocator_mesos_resources_disk_offered_or_allocated{state=\"leader\"}",
     "legendFormat": "Offered and allocated"
    }
   ]
  }
 ]
}