{
 "title": "Mesos Masters Summary",
 "tags": [
  "mesos",
  "masters",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Interval", "query": "2m, 1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Mesos Masters Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(mesos_master_uptime_secs) by (instance)"
    }
   ]
  },
  {
   "title": "Mesos Master Election",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mesos_master_elected", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_tasks_staging)",
     "legendFormat": "Staging"
    },
    {
     "expr": "sum(mesos_master_tasks_starting)",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(mesos_master_tasks_running)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(mesos_master_tasks_unreachable)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Terminal tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_tasks_finished)",
     "legendFormat": "Finished"
    },
    { "expr": "sum(mesos_master_tasks_failed)", "legendFormat": "Failed" },
    { "expr": "sum(mesos_master_tasks_gone)", "legendFormat": "Gone" },
    {
     "expr": "sum(mesos_master_tasks_gone_by_operator)",
     "legendFormat": "Gone by operator"
    },
    {
     "expr": "sum(mesos_master_tasks_dropped)",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(mesos_master_tasks_killing)",
     "legendFormat": "Killing"
    },
    { "expr": "sum(mesos_master_tasks_killed)", "legendFormat": "Killed" },
    { "expr": "sum(mesos_master_tasks_lost)", "legendFormat": "Lost" },
    { "expr": "sum(mesos_master_tasks_error)", "legendFormat": "Error" }
   ]
  },
  {
   "title": "Number of frameworks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_frameworks_active)",
     "legendFormat": "frameworks"
    }
   ]
  },
  {
   "title": "Number of agents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_slaves_connected)",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(mesos_master_slaves_disconnected)",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "sum(mesos_master_slaves_active)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(mesos_master_slaves_inactive)",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum(mesos_master_slaves_unreachable)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_event_queue_dispatches)",
     "legendFormat": "Dispatches"
    },
    {
     "expr": "sum(mesos_master_event_queue_http_requests)",
     "legendFormat": "HTTP Requests"
    },
    {
     "expr": "sum(mesos_master_event_queue_messages)",
     "legendFormat": "Messages"
    }
   ]
  }
 ]
}