{
 "title": "Admin Router Details Upstreams",
 "tags": [
  "dc/os",
  "detail",
  "adminrouter",
  "upstreams"
 ],
 "time": { "from": "2019-01-31T23:17:08.849Z", "to": "2019-02-01T01:33:07.935Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   {
    "name": "master_prometheus",
    "label": "Prometheus Instance",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},instance)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_vts_upstream_request_seconds{dcos_component_name=\"Admin Router\"},upstream)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Admin Router Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin Router Nginx Load: $master_prometheus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_server_requests_total{host=\"*\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_server_request_seconds{host=\"*\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Admin Router Nginx Status Percentage: $master_prometheus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_server_requests_total{host=\"*\",code=\"5xx\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_server_requests_total{host=\"*\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_server_requests_total{host=\"*\",code=\"4xx\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_server_requests_total{host=\"*\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_server_requests_total{host=\"*\",code=\"3xx\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_server_requests_total{host=\"*\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_server_requests_total{host=\"*\",code=\"2xx\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_server_requests_total{host=\"*\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "IAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IAM Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"iam\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "IAM Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"iam\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "CockroachDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CockroachDB Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"cockroachdb\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "CockroachDB Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"cockroachdb\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Cosmos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Cosmos Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{backend=~\"[^ ]+:7070\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Cosmos Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:7070\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS CA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "DC/OS CA Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"certificate_authority\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS CA Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"certificate_authority\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "DC/OS Diagnostics Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"dcos_diagnostics\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS Diagnostics Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_diagnostics\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS Licensing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "DC/OS Licensing Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"licensing\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS Licensing Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"licensing\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "DC/OS Net Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"dcos_net\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS Net Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"dcos_net\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "DC/OS Registry Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"registry\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS Registry Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"registry\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "DC/OS Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "DC/OS Secrets Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"/run/dcos/dcos-secrets.sock\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "DC/OS Secrets Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"/run/dcos/dcos-secrets.sock\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Exhibitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Exhibitor Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"exhibitor\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Exhibitor Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"exhibitor\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Marathon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Marathon Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{backend=~\"[^ ]+:(8080|8443)\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Marathon Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(8080|8443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Mesos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Mesos Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{backend=~\"[^ ]+:5050\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Mesos Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:5050\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "MesosDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "MesosDNS Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"mesos_dns\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "MesosDNS Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"mesos_dns\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Metronome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Metronome Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{backend=~\"[^ ]+:(9090|9443)\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Metronome Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{backend=~\"[^ ]+:(9090|9443)\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  },
  { "title": "Pkgpanda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Pkgpanda Upstream Load: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"total\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}[$rate_interval]))",
     "legendFormat": "Throughput"
    },
    {
     "expr": "max(nginx_vts_upstream_request_seconds{upstream=\"pkgpanda\",dcos_component_name=\"Admin Router\",instance=~\"$master_prometheus\"}) * 1000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Pkgpanda Upstream Status Percentage: $node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "percent", "label": "log % HTTP status" }
   ],
   "targets": [
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"5xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "5xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"4xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "4xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"3xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "3xx"
    },
    {
     "expr": "max((rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"2xx\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]) / ignoring(code) rate(nginx_vts_upstream_requests_total{upstream=\"pkgpanda\",code=\"total\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100)",
     "legendFormat": "2xx"
    }
   ]
  }
 ]
}