{
 "title": "Admin Router: Details DC/OS Service Proxy Responses",
 "tags": [
  "dc/os",
  "detail",
  "adminrouter",
  "service",
  "responses"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "DC/OS Master Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_service_status_requests_total{dcos_component_name=\"Admin Router\"},service)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(nginx_service_status_requests_total{service=\"$service\",dcos_component_name=\"Admin Router\"},backend)"
   },
   {
    "name": "status",
    "label": "HTTP Status",
    "query": "label_values(nginx_upstream_status_requests_total{dcos_component_name=\"Admin Router\"},status)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "HTTP ( $status ) Status Request Latency Distribution | Proxied to ( $service => $backend ) through DC/OS Master Nodes ( $node )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "log Percent" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": ">25s"
    },
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "5s-25s"
    },
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "1s-5s"
    },
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "200ms-1s"
    },
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "40ms-200ms"
    },
    {
     "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "8ms-40ms"
    },
    {
     "expr": "sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",status=~\"$status\",backend=~\"$backend\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "<8ms"
    }
   ]
  },
  {
   "title": "HTTP Status Distribution | Proxied to ( $service => $backend ) through DC/OS Master Nodes ( $node )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "log Percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"5.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"4.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"3.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"2.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "HTTP ( $status ) Status Code Rate | Proxied to ( $service => $backend ) through DC/OS Master Nodes ( $node )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "User Agent HTTP ( $status ) Status Code Rate | Proxied to ( $service => $backend ) through DC/OS Master Nodes ( $node )",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(nginx_service_useragent_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status,useragent)",
     "legendFormat": "<b>{{status}}</b>      {{useragent}}"
    }
   ]
  },
  {
   "title": "URI HTTP ( $status ) Status Code Rate | Proxied to ( $service => $backend ) through DC/OS Master Nodes ( $node )",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(nginx_service_uri_requests_total{service=~\"$service\",backend=~\"$backend\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status,uri)",
     "legendFormat": "<b>{{status}}</b>     {{uri}}"
    }
   ]
  }
 ]
}