{
 "title": "AdminRouter: Details Service Status",
 "tags": [
  "dc/os",
  "adminrouter",
  "detail",
  "service",
  "status"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nginx_service_status_requests_total{dcos_component_name=\"Admin Router\"},service)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "$service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "Service HTTP Request Throughput: $node - $service",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
     "repeat": "node",
     "yaxes": [
      { "format": "none", "label": "Requests/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "Service HTTP Request Latency Distribution: $node - $service",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": ">25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5s-25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "1s-5s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "200ms-1s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "40ms-200ms"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "8ms-40ms"
      },
      {
       "expr": "sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "<8ms"
      }
     ]
    },
    {
     "title": "Service HTTP Status Distribution: $node - $service",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"5.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"4.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"3.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"2.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"1.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(rate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100"
      }
     ]
    },
    {
     "title": "Upstream Throughput: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "Requests/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "Upstream HTTP Latency: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": ">25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5s-25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "1s-5s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "200ms-1s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "40ms-200ms"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "8ms-40ms"
      },
      {
       "expr": "sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "<8ms"
      }
     ]
    },
    {
     "title": "Service HTTP Status: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"5.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"4.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"3.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"2.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"1.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(rate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100"
      }
     ]
    },
    {
     "title": "Upstream Throughput: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "Requests/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "Upstream HTTP Latency: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": ">25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"25\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5s-25s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"5\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "1s-5s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"1\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "200ms-1s"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.2\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "40ms-200ms"
      },
      {
       "expr": "(sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.04\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval]))-sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])))/sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "8ms-40ms"
      },
      {
       "expr": "sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",backend=~\".+\",le=\"0.008\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_request_duration_seconds_bucket{service=~\"$service\",backend=~\".+\",le=\"+Inf\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "<8ms"
      }
     ]
    },
    {
     "title": "Service HTTP Status: $node",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percent", "label": "log Percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"5.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "5xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"4.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"3.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"2.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",status=~\"1.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(rate(nginx_service_status_requests_total{service=~\"$service\",backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100"
      }
     ]
    }
   ]
  }
 ]
}