{
 "title": "Admin Router: Details Runtime",
 "description": "Runtime",
 "tags": [
  "dc/os",
  "detail",
  "adminrouter",
  "runtime"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   {
    "name": "master_prometheus",
    "label": "Prometheus Instance",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},instance)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Instances: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(nginx_vts_info{dcos_component_name=\"Admin Router\",host=~\"$node\"})",
     "legendFormat": "Number of live instances"
    }
   ]
  },
  {
   "title": "Nginx Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "nginx_vts_info{version=\"1.13.6\",dcos_component_name=\"Admin Router\",host=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - nginx_vts_start_time_seconds{dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Uptime: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "time() - nginx_vts_start_time_seconds{dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Connections (max): $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_connections{status=~\"active\",dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Connections (max): $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "nginx_vts_main_connections{status=~\"active\",dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Connection State (max): $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(nginx_vts_main_connections{status=~\"reading|writing|waiting\",dcos_component_name=\"Admin Router\",host=~\"$node\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Active Connection State (max): $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "max(nginx_vts_main_connections{status=~\"reading|writing|waiting\",dcos_component_name=\"Admin Router\",host=~\"$node\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "VTS Module Shared Memory Size: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "Shared memory size" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_shm_usage_bytes{shared=\"used_size\",dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VTS Module Shared Memory Size: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "nginx_vts_main_shm_usage_bytes{shared=\"used_size\",dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}