{
 "title": "/AdminRouter/AdminRouter-Details-Upstream-Responses",
 "tags": [
  "dc/os",
  "detail",
  "adminrouter",
  "upstream",
  "responses"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": "label_values(nginx_upstream_backend_requests_total{dcos_component_name=\"Admin Router\"},upstream)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(nginx_upstream_backend_requests_total{upstream=\"$upstream\",dcos_component_name=\"Admin Router\"},backend)"
   },
   {
    "name": "status",
    "label": "HTTP Status",
    "query": "label_values(nginx_upstream_status_requests_total{dcos_component_name=\"Admin Router\"},status)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Upstream HTTP Status: $node - $upstream ($backend)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "log Percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{upstream=~\"$upstream\",status=~\"5.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_upstream_backend_requests_total{upstream=~\"$upstream\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{upstream=~\"$upstream\",status=~\"4.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_upstream_backend_requests_total{upstream=~\"$upstream\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{upstream=~\"$upstream\",status=~\"3.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_upstream_backend_requests_total{upstream=~\"$upstream\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{upstream=~\"$upstream\",status=~\"2.*\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) / sum(irate(nginx_upstream_backend_requests_total{upstream=~\"$upstream\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) * 100",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "Upstream HTTP Responses: $node - $upstream ($backend)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{upstream=~\"$upstream\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Useragent Request Rate: $status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_useragent_requests_total{upstream=~\"$upstream\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status,useragent)",
     "legendFormat": "<b>{{status}}</b>      {{useragent}}"
    }
   ]
  },
  {
   "title": "URI Request Rate: $status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_uri_requests_total{upstream=~\"$upstream\",status=~\"$status\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (status,uri)",
     "legendFormat": "<b>{{status}}</b>     {{uri}}"
    }
   ]
  }
 ]
}