{
 "title": "/AdminRouter/AdminRouter-Summary",
 "tags": [
  "dc/os",
  "summary",
  "adminrouter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(nginx_vts_info{dcos_component_name=\"Admin Router\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Instances: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count(nginx_vts_info{dcos_component_name=\"Admin Router\",host=~\"$node\"})",
     "legendFormat": "Number of live instances"
    }
   ]
  },
  {
   "title": "Admin Router Instance Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "content": "Number of Admin Router instances running on DC/OS master nodes. This should always match the number of expected DC/OS master nodes in the cluster."
  },
  {
   "title": "Uptime: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s", "label": "log Time" }
   ],
   "targets": [
    {
     "expr": "time() - nginx_vts_start_time_seconds{dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Admin Router Uptime",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "content": "Admin Router uptime on a logarithmic scale. This graph is best for detecting Admin Router restarts."
  },
  {
   "title": "Active Connections (max): $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_connections{status=~\"active\",dcos_component_name=\"Admin Router\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Admin Router Active Connections",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "content": "Number of connections managed by Admin Router. Active connections are the important metrics here since the DC/OS configuration limits them to a maximum of 1024. Beyond this number no new connections will be opened."
  },
  {
   "title": "Nginx Throughput: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_status_requests_total{dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (host) + sum(irate(nginx_upstream_status_requests_total{dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (host) + sum(irate(nginx_service_status_requests_total{dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Admin Router Nginx Throughput",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Nginx throughput measured in requests per second. This is the total request rate towards each Admin Router instance. This includes request handled by each configured server directly plus requests that went to an upstream."
  },
  {
   "title": "Server Throughput: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(sum(irate(nginx_server_status_requests_total{dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (host,server) or sum(irate(nginx_upstream_status_requests_total{backend=\"\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (host,upstream)) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Admin Router Server Throughput",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "content": "Server throughput measured in requests per second. This is concerned with requests that are served by Admin Router itself, not going to any of the upstreams found in the upstream tab."
  },
  {
   "title": "Upstream Throughput: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_status_requests_total{backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (upstream)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Admin Router Upstream Throughput",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "content": "Stacked upstream throughput measured as requests per second going to each upstream server aggregated over all master nodes. This graph helps to identify upstreams that are particularly active."
  },
  {
   "title": "Service Throughput: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_service_status_requests_total{backend=~\".+\",dcos_component_name=\"Admin Router\",host=~\"$node\"}[$rate_interval])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Admin Router Service Throughput",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "content": "Stacked service throughput measured as requests per second going to each service upstream server aggregated over all master nodes. This graph helps to identify services that are particularly active."
  }
 ]
}