{
 "title": "/Storage-Summary",
 "tags": [
  "dc/os",
  "summary",
  "storage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DSS uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_sched_uptime" }
   ]
  },
  {
   "title": "Storage service uptime",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "content": "Shows the time since the last restart of the storage service.\n\nThis metric should always increase. If the metric drops to zero, the service has restarted and some time of service unavailability might be observed afterwards."
  },
  {
   "title": "DSS/Mesos Heartbeats",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "dss_sched_events_heartbeat_process_count"
    }
   ]
  },
  {
   "title": "Rate of heartbeat events from the Mesos master",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "content": "This metric should always increase as long as the storage service is running.\n\nIt will drop to zero when the service restarts, see the storage service uptime.\n\nIf the metric does not increase for extended periods of time, the service might have lost connection to the Mesos master and might need to be restarted."
  },
  {
   "title": "Scheduler event rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dss_sched_events_offers_samples[2m])",
     "legendFormat": "Offer events"
    },
    {
     "expr": "rate(dss_sched_events_samples[2m])",
     "legendFormat": "All scheduler events"
    }
   ]
  },
  {
   "title": "Rate of some events from the Mesos master",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "content": "This panel shows the rate of any kind of event received from the Mesos master, and the rate of offer events.\n\nThis metric should remain mostly flat and non-zero during normal storage service operation.\n\n\nWhen a storage operation is performed the rate might increase temporarily, but should drop to its previous value after the operation is done. If operations are pending, but no offer events are observed, the service might be starved for resources.\nIf this metric drops to zero, the service might have lost contact to the Mesos master and might need to be restarted, also see the service heartbeat metric."
  },
  {
   "title": "DSS ACKs Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_sched_acks_qlen" }
   ]
  },
  {
   "title": "Size of the service ACK queue",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "content": "This metric is related to the number of unfinished storage servive operations.\n\nThe metric should be at zero during normal service operation, but might increase temporarily when storage operations are performed.\n\nIf the metric remains non-zero for extended periods of time, the scheduler might have lost contact to the Mesos master, Mesos agents might be unreachable, or CSI plugins on Mesos agents might have become unresponsive."
  },
  {
   "title": "Storage dominant role shares",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_roles_shares_dominant{role_name=\"dcos-storage\"}",
     "legendFormat": "dcos-storage"
    },
    {
     "expr": "mesos_allocator_roles_shares_dominant{role_name=\"dcos-storage/claimed\"}",
     "legendFormat": "dcos-storage/claimed"
    }
   ]
  },
  {
   "title": "Resource usage of storage service",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "content": "This metric measures the storage service's usage of resources when performing storage operations. Resources to run the storage service itself are not included here.\n\nThe metric should be zero during normal operation, but migtht become non-zero when storage operations are performed.\n\nIf this metric becomes larger than zero for long durations of time, the storage service might not be able to perform storage operations quickly anymore, and might need to be restarted, also see the offer rate metric."
  }
 ]
}