{
 "title": "Edge-LB: Go Runtime - overview",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath)" },
   {
    "name": "component",
    "label": "Component",
    "query": "apiserver,dcos-template,lbmgr,cloud-controller,mesos-listener"
   },
   { "name": "poolName", "label": "Pool name", "query": "label_values(poolName)" },
   {
    "name": "poolServer",
    "label": "Pool Server",
    "query": "label_values(dcos_edgelb_go_info{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",component=\"lbmgr\"}, task_name)"
   }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_process_cpu_seconds_total{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_process_cpu_seconds_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Process uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - dcos_edgelb_process_start_time_seconds{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "time() - dcos_edgelb_process_start_time_seconds{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_process_resident_memory_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_process_resident_memory_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_process_virtual_memory_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_process_virtual_memory_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "File descriptors in use and the limit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_process_open_fds{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_process_open_fds{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    },
    {
     "expr": "dcos_edgelb_process_max_fds{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}} limit"
    },
    {
     "expr": "dcos_edgelb_process_max_fds{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}} limit@{{poolName}}:{{task_name}}"
    }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_threads{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_threads{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_goroutines{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_goroutines{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  }
 ]
}