{
 "title": "Edge-LB: Apiserver - Cloud Controller",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath)" },
   { "name": "poolName", "label": "Pool name", "query": "label_values(poolName)" },
   { "name": "grpc_method", "label": "gRPC Method", "query": "label_values(grpc_method)" }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of Pending Pool Load Balancers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_dirty_pool_load_balancers{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Pool Update Inbound Rate from APIServer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_pool_updates_total{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\", poolName=~\"$poolName\"}[5m])) by(kind, poolName)",
     "legendFormat": "{{poolName}}:{{kind}}"
    }
   ]
  },
  {
   "title": "Metadata Update Rate from Lbmgr",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dcos_edgelb_dropped_metadata_updates_total{component=~\"cloud-controller\",applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}[1m]))",
     "legendFormat": "dropped"
    },
    {
     "expr": "sum(rate(dcos_edgelb_processed_metadata_updates_total{component=~\"cloud-controller\",applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}[1m]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(dcos_edgelb_ineffective_metadata_updates_total{component=~\"cloud-controller\",applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}[1m]))",
     "legendFormat": "ineffective"
    }
   ]
  },
  {
   "title": "gRPC Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC Request Inbound Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_grpc_server_handled_total{component=~\"cloud-controller\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",grpc_method=~\"$grpc_method\"}[5m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Unary Request Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_grpc_server_handled_total{component=\"cloud-controller\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_type=\"unary\", grpc_code!=\"OK\", grpc_method=~\"$grpc_method\"}[5m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Average Response Stream Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dcos_edgelb_grpc_server_msg_sent_total{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", grpc_type=\"server_stream\", dcos_cluster_name=~\"$dcos_cluster_name\"}[10m])) by (grpc_service)\r\n /\r\nsum(rate(dcos_edgelb_grpc_server_started_total{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", grpc_type=\"server_stream\", dcos_cluster_name=~\"$dcos_cluster_name\"}[10m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Slow Unary Queries (>1s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dcos_edgelb_grpc_server_handling_seconds_bucket{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"UpdateMetadata\", le=\"1\"}[5m])) by (grpc_service) \r\n - \r\nsum(rate(dcos_edgelb_grpc_server_handling_seconds_count{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"UpdateMetadata\"}[5m])) by (grpc_service)\r\n",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Provider AWS API Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "AWS API Query Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dcos_edgelb_cloud_provider_aws_api_requests_total{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}[1m])) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "AWS queries taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_cloud_provider_aws_api_request_duration_seconds_bucket{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\", le=\"+Inf\"}[5m])) by (request) - sum(irate(dcos_edgelb_cloud_provider_aws_api_request_duration_seconds_bucket{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\", le=\"1\"}[5m])) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "AWS API Query Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dcos_edgelb_cloud_provider_aws_api_request_errors_total{component=~\"cloud-controller\", applicationPath=~\"$applicationPath\", dcos_cluster_name=~\"$dcos_cluster_name\"}[1m])) by (request)",
       "legendFormat": "{{request}}"
      }
     ]
    }
   ]
  }
 ]
}