{
 "title": "Edge-LB: Apiserver - Dcos-template",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name) "
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath) " }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Defined templates count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dcos_edgelb_tracked_templates_count{component=~\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Templates configuration change rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_config_change_notifications_total{component=~\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Template contents change rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_template_change_notifications_total{component=~\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])  )by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Template rendering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average template rendering time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_template_rendering_time_seconds_sum{component=\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"} / dcos_edgelb_template_rendering_time_seconds_count{component=\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(dcos_cluster_name,applicationPath,status)",
       "legendFormat": "[{{status}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Template rendering rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_template_rendering_time_seconds_count{component=\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(dcos_cluster_name,applicationPath,status)",
       "legendFormat": "[{{status}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Template renderings taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_template_rendering_time_seconds_bucket{component=\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",le=\"1\"}[5m])) by (dcos_cluster_name,applicationPath,status) - sum(irate(dcos_edgelb_template_rendering_time_seconds_count{component=\"dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])) by (dcos_cluster_name,applicationPath,status)",
       "legendFormat": "[{{status}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    }
   ]
  }
 ]
}