{
 "title": "Edge-LB: Apiserver - Apiserver process",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name) "
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath) " },
   {
    "name": "apiHandler",
    "label": "API handler",
    "query": "label_values(dcos_edgelb_http_request_duration_seconds_count, handler)"
   },
   { "name": "grpcMethod", "label": "gRPC Method", "query": "label_values(grpc_method)" }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pools count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_pools_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}",
     "legendFormat": "[{{kind}}] {{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Pool templates count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_pool_templates_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "HTTP API requests rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_http_request_duration_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"}[5m])) by (dcos_cluster_name, applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "HTTP API requests in-flight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dcos_edgelb_http_requests_inflight{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"}) by (dcos_cluster_name, applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "ZooKeeper operations rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_zkrequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Filesystem operations rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_filerequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Apiserver state operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_state_operations_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(dcos_cluster_name,applicationPath)",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "HTTP API requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP responses codes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_http_request_duration_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"}[5m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "API endpoint requests rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_http_request_duration_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"}[5m])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "API endpoint average response time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_http_request_duration_seconds_sum{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"})by(handler) / sum(dcos_edgelb_http_request_duration_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"})by(handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "API endpoint requests taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_http_request_duration_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\",le=\"1\"}[5m])) by (handler) - sum(irate(dcos_edgelb_http_request_duration_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", handler=~\"$apiHandler\"}[5m])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata updates rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_grpc_server_handled_total{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"SendMetadata\"}[5m])",
       "legendFormat": "[{{grpc_code}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Average metadata updates call duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_grpc_server_handling_seconds_sum{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"SendMetadata\"} /dcos_edgelb_grpc_server_handling_seconds_count{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"SendMetadata\"} ",
       "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Metadata updates taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_grpc_server_handling_seconds_bucket{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"SendMetadata\",le=\"1\"}[5m])) by (dcos_cluster_name,applicationPath) - sum(irate(dcos_edgelb_grpc_server_handling_seconds_count{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"SendMetadata\"}[5m])) by (dcos_cluster_name,applicationPath)",
       "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Pool data messages streamed to clients rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_grpc_server_msg_sent_total{component=\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", grpc_method=\"ConfigStream\"}[5m])",
       "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem operations rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_filerequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ZooKeeper operations rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_zkrequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filesystem operations errors rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_filerequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",status=\"fail\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ZooKeeper operations errors rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_zkrequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",status=\"fail\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filesystem operations average duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_filerequests_time_seconds_sum{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type) / sum(dcos_edgelb_filerequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ZooKeeper operations average duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_zkrequests_time_seconds_sum{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type) / sum(dcos_edgelb_zkrequests_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filesystem operations taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_filerequests_time_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",le=\"1\"}[5m])) by (type) - sum(irate(dcos_edgelb_filerequests_time_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "ZooKeeper operations taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_zkrequests_time_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",le=\"1\"}[5m])) by (type) - sum(irate(dcos_edgelb_zkrequests_time_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Apiserver state operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apiserver state operations rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_state_operations_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Apiserver state operations average duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_state_operations_time_seconds_sum{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type) / sum(dcos_edgelb_state_operations_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"})by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Apiserver state operations taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_state_operations_time_seconds_bucket{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",le=\"1\"}[5m]))by(type) - sum(irate(dcos_edgelb_state_operations_time_seconds_count{component=~\"apiserver\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m]))by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}