{
 "title": "Edge-LB: Go Runtime - memory usage details",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath)" },
   {
    "name": "component",
    "label": "Component",
    "query": "apiserver,dcos-template,lbmgr,cloud-controller,mesos-listener"
   },
   { "name": "poolName", "label": "Pool name", "query": "label_values(poolName)" },
   {
    "name": "poolServer",
    "label": "Pool Server",
    "query": "label_values(dcos_edgelb_go_info{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",component=\"lbmgr\"}, task_name)"
   }
  ]
 },
 "panels": [
  { "title": "Related dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Heap bytes allocated and still in use",
   "type": "graph",
   "description": "Shows how much bytes of memory is allocated on the Heap for the Objects. Counts all reachable heap objects plus unreachable objects, GC has not yet freed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_heap_alloc_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_heap_alloc_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Heap bytes released to OS",
   "type": "graph",
   "description": "Shows how many bytes of idle spans were returned to the OS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_heap_released_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_heap_released_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  { "title": "Allocator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "malloc`s rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_go_memstats_mallocs_total{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_go_memstats_mallocs_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "free's rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_go_memstats_frees_total{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_go_memstats_frees_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Total number of bytes obtained from system",
   "type": "graph",
   "description": "How many bytes of memory in total is taken from system by Go.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_sys_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_sys_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  { "title": "Memory objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Number of allocated objects",
   "type": "graph",
   "description": "Shows how many objects are allocated on the heap. This changes as GC is performed and new objects are allocated.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_heap_objects{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_heap_objects{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Total number of pointer lookups.",
   "type": "graph",
   "description": "Counts how many pointer dereferences happened",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_go_memstats_lookups_total{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_go_memstats_lookups_total{component=\"lbmgr\",poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  { "title": "Memory spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "`In-use` memory spans memory use",
   "type": "graph",
   "description": "Shows how many bytes are in in-use spans",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_heap_inuse_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_heap_inuse_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "`Idle` memory spans memory use",
   "type": "graph",
   "description": "Shows how many bytes are in idle spans",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_heap_idle_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_heap_idle_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"} ",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "`stack-memory` memory spans memory use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_stack_inuse_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_stack_inuse_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_go_gc_duration_seconds_sum{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])\n",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_go_gc_duration_seconds_sum{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(dcos_edgelb_go_gc_duration_seconds_count{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}[5m])\n",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "irate(dcos_edgelb_go_gc_duration_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",task_name=~\"$poolServer\"}[5m])",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "GC CPU time percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_gc_cpu_fraction{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_gc_cpu_fraction{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "GC system metadata memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_go_memstats_gc_sys_bytes{component=~\"apiserver|cloud-controller|mesos-listener|dcos-template\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",component=~\"$component\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "dcos_edgelb_go_memstats_gc_sys_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
     "legendFormat": "{{component}}@{{poolName}}:{{task_name}}"
    }
   ]
  }
 ]
}