{
 "title": "Edge-LB: Apiserver - Mesos Listener",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name) "
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath) " }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Clients connected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcos_edgelb_clients_connected{component=~\"mesos-listener\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}",
     "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
    }
   ]
  },
  {
   "title": "Internal state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal state objects count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_state_objects{component=\"mesos-listener\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}",
       "legendFormat": "[{{kind}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Internal state change rate",
     "type": "graph",
     "description": "The graph presents how often the internal state of mesos-listener is updated due to changes in the state of the cluster",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_state_updates_total{component=\"mesos-listener\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])",
       "legendFormat": "{{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mesos streaming API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesos streaming API events",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_mesos_stream_events_total{component=~\"mesos-listener\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])",
       "legendFormat": "[{{kind}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    },
    {
     "title": "Mesos streaming API reconnects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_mesos_reconnects_total{component=~\"mesos-listener\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\"}[5m])",
       "legendFormat": "[{{kind}}] {{dcos_cluster_name}}:{{applicationPath}}"
      }
     ]
    }
   ]
  }
 ]
}