{
 "title": "Edge-LB: Pool Server",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath)" },
   { "name": "poolName", "label": "Pool name", "query": "label_values(poolName)" },
   {
    "name": "poolServer",
    "label": "Pool Server",
    "query": "label_values(dcos_edgelb_go_info{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",component=\"lbmgr\"}, task_name)"
   },
   { "name": "grpcMethod", "label": "gRPC Method", "query": "label_values(grpc_method)" }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "HaProxy reloads rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_reload_requests_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "{{poolName}}"
    }
   ]
  },
  {
   "title": "Metadata updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_metadata_updates_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",kind=\"update\"}[5m]))by(poolName,task_name)",
     "legendFormat": "{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "gRPC connection reconnects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_grpc_reconnects_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(poolName,task_name)",
     "legendFormat": "{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "Failed metadata updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_metadata_updates_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",kind=\"failed\"}[5m]))by(poolName,task_name)",
     "legendFormat": "{{poolName}}:{{task_name}}"
    }
   ]
  },
  {
   "title": "AWS queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "AWS data change rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_awsfetch_updated{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName,task_name)",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Query rate by pool server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_awsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(poolName,task_name)",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Query rate by node and status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_awsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(host,query_status)",
       "legendFormat": "[{{query_status}}] {{host}}"
      }
     ]
    },
    {
     "title": "AWS queries taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_awsrequests_time_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",le=\"+Inf\"}[5m]))by(host) - sum(irate(dcos_edgelb_awsrequests_time_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",le=\"1\"}[5m]))by(host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "AWS query average time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_awsrequests_time_seconds_sum{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (host) / sum(dcos_edgelb_awsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IP information queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP data change rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_ipsfetch_updated{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName,task_name)",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Query rate by pool server",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_ipsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(poolName,task_name)",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Query rate by node and status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_ipsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(host,query_status)",
       "legendFormat": "[{{query_status}}] {{host}}"
      }
     ]
    },
    {
     "title": "IP queries taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_ipsrequests_time_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",le=\"+Inf\"}[5m]))by(host) - sum(irate(dcos_edgelb_ipsrequests_time_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",le=\"1\"}[5m]))by(host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "IP queries average time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_ipsrequests_time_seconds_sum{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (host) / sum(dcos_edgelb_ipsrequests_time_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Haproxy Reloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reloads rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_reload_requests_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Throttled reloads rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_reloads_throtled_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Failed reloads rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_failed_requests_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Received config size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_received_config_size_bytes{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC client method call rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_grpc_client_started_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\", grpc_method=~\"$grpcMethod\"}[5m])",
       "legendFormat": "[{{grpc_method}}] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC call status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_grpc_client_handled_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=~\"$grpcMethod\"}[5m])) by (grpc_code, poolName,task_name)",
       "legendFormat": "[{{grpc_code}}] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC stream messages rate - sent by the client",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_grpc_client_msg_sent_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"StreamLBConfig\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC stream messages rate - received by the client",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_grpc_client_msg_received_total{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"StreamLBConfig\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC unary call average duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(dcos_edgelb_grpc_client_handling_seconds_sum{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"UpdateMetadata\"}[5m]) / rate(dcos_edgelb_grpc_client_handling_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"UpdateMetadata\"}[5m])",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC unary messages taking longer than 1s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (sum(rate(dcos_edgelb_grpc_client_handling_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"UpdateMetadata\",le=\"1\"}[5m]))by(poolName,task_name) / sum(rate(dcos_edgelb_grpc_client_handling_seconds_count{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"UpdateMetadata\"}[5m]))by(poolName,task_name))*100",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "gRPC unary message time breakdown",
     "type": "graph",
     "description": "This graph presents the rate of requests that were completed within the given time. E.g. the 0.1s graph contains all the requests that happened in less and 0.05s and 0.05s-0.1s, 0.25s graph contains all the requests for 0.1s graph plus the requests between 0.1s and 0.25s, etc...",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dcos_edgelb_grpc_client_handling_seconds_bucket{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\",grpc_method=\"UpdateMetadata\"}[5m]))by(le) ",
       "legendFormat": "{{le}}s"
      }
     ]
    }
   ]
  },
  {
   "title": "Healtchecking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthchecks rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(dcos_edgelb_healthcheck_called{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]) ",
       "legendFormat": "[called] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "irate(dcos_edgelb_healthcheck_failed{component=\"lbmgr\",poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]) ",
       "legendFormat": "[failed] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "irate(dcos_edgelb_healthcheck_successful{component=\"lbmgr\",poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]) ",
       "legendFormat": "[successfull] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Socket i/o time total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_healthcheck_time_total_mean{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[mean] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "dcos_edgelb_healthcheck_time_total_stddev{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[stddev] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Socket dial time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_healthcheck_time_dial_mean{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[mean] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "dcos_edgelb_healthcheck_time_dial_stddev{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[stddev] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Socket write time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_healthcheck_time_write_mean{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[mean] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "dcos_edgelb_healthcheck_time_write_stddev{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[stddev] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Socket read time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_healthcheck_time_read_mean{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[mean] {{poolName}}:{{task_name}}"
      },
      {
       "expr": "dcos_edgelb_healthcheck_time_read_stddev{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "[stddev] {{poolName}}:{{task_name}}"
      }
     ]
    },
    {
     "title": "Haproxy reply size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_healthcheck_haproxy_reply_size{component=\"lbmgr\", poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "{{poolName}}:{{task_name}}"
      }
     ]
    }
   ]
  }
 ]
}