{
 "title": "Marathon Detail",
 "tags": [
  "marathon",
  "detail",
  "dc/os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Interval", "query": "1m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Heap (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_jvm_memory_heap_used_gauge_bytes{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_deployments_dismissed_counter{task_name=~\".+\"})",
     "legendFormat": "dismissed {{task_name}}"
    },
    {
     "expr": "max by (task_name) (marathon_deployments_active_gauge{task_name=~\".+\"})",
     "legendFormat": "current {{task_name}}"
    }
   ]
  },
  {
   "title": "Task Launch ($min_interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(marathon_tasks_launched_counter{task_name=~\".+\"}[$min_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_jvm_threads_active_gauge{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "HTTP traffic (MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_http_requests_size_counter_bytes{task_name=~\".+\"}) / 1024 / 1024",
     "legendFormat": "read {{task_name}}"
    },
    {
     "expr": "max by (task_name) (marathon_http_responses_size_counter_bytes{task_name=~\".+\"}) / 1024 / 1024",
     "legendFormat": "written {{task_name}}"
    }
   ]
  },
  {
   "title": "Launched tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_tasks_launched_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Uptime (m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_uptime_gauge_seconds{task_name=~\".+\"}) / 60",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}