{
 "title": "DC/OS Calico",
 "tags": [
  "calico",
  "dc/os"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(felix_host)" }
   ]
  },
  {
   "title": "Exec Time p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(felix_exec_time_micros{quantile=\"0.99\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Local Selectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_selectors{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Local Policies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_policies{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_endpoints{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Update Apply Duration p99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_apply_time_seconds{quantile=\"0.99\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Update Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(felix_int_dataplane_failures{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_messages{instance=~\"$instance\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Message Batch Sizes p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_msg_batch_size{quantile=\"0.99\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "IP Tables Save and Restore Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(felix_iptables_save_errors{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "increase(felix_iptables_restore_errors{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Set Command Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_ipset_errors{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Tables Save and Restore Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(felix_iptables_save_calls{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}:Save"
    },
    {
     "expr": "rate(felix_iptables_restore_calls{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}:Restore"
    }
   ]
  },
  {
   "title": "IP Tables Active Chains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_chains{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IP Tables Active Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "felix_iptables_rules", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active IP Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_ipsets_calico{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}