{
 "title": "Networking: VM",
 "tags": [ "erlang-details" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(erlang_vm_process_count, host)"
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{host=~\"$host\"}[$rate])",
     "legendFormat": "Max. Number GCs"
    }
   ]
  },
  {
   "title": "Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{host=~\"$host\"}",
     "legendFormat": "Process Count"
    },
    {
     "expr": "erlang_vm_process_limit{host=~\"$host\"}",
     "legendFormat": "Process Limit"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{host=~\"$host\"}[$rate])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{host=~\"$host\"}[$rate])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 1 },
   "content": "This set of panels shows VM CPU consumption.\n \n**VM GC**: Shows the number of GCs performed and how many bytes they reclaimed. With multiple hosts, shows the `max` bytes reclaimed and the `max` number of GC among the hosts.\n\n**Queues Length**: Shows the queue length of the selected host.\n\n**Load**: shows the number of Reductions and Context Switches performed by the [VM scheduler](https://hamidreza-s.github.io/erlang/scheduling/real-time/preemptive/migration/2016/02/09/erlang-scheduler-details.html).\n\n**Processes**: shows the total number of processes and ports ready to run at any given run-queue, the total number of process current running at the node and the limit in number of processes when set."
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{host=~\"$host\"}",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Uptime: Longest running VMs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(5,erlang_vm_statistics_wallclock_time_milliseconds/1000/60/60/24)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_statistics_wallclock_time_milliseconds{host=~\"$host\"}/1000/60/60/24",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 16 },
   "content": "This set of panels shows uptime.\n \n**Uptime**: This host's uptime in hours.\n\n**Uptime: Longest Running VMs**: Longest living VMs based on top 5 uptime.\n\n**Uptime: Most Recent Restarts**: Most recent restarts based on bottom 5 uptime."
  },
  {
   "title": "Uptime: Most Recent Restarts",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "bottomk(5,erlang_vm_statistics_wallclock_time_milliseconds/1000/60/60/24)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{host=~\"$host\", kind=\"processes\"}",
     "legendFormat": "Processes Memory {{host}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{host=~\"$host\", usage=\"atom\"}",
     "legendFormat": "Atoms {{host}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{host=~\"$host\", usage=\"binary\"}",
     "legendFormat": "Binary {{host}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{host=~\"$host\", usage=\"code\"}",
     "legendFormat": "Code {{host}}"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{host=~\"$host\", usage=\"ets\"}",
     "legendFormat": "ETS {{host}}"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "content": "This set of panels shows VM Memory consumption.\n\n**VM Memory**: This graph shows the total memory used by the system + `processes`. The `system` memory is further broken down according to the type of usage `atoms`, `binary`, `code` and `ets` tables."
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{host=~\"$host\"}[$rate])",
     "legendFormat": "Output Bytes {{host}}"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{host=~\"$host\"}[$rate])",
     "legendFormat": "Received Bytes {{host}}"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_port_limit{host=~\"$host\"}",
     "legendFormat": "Max Ports {{host}}"
    },
    {
     "expr": "erlang_vm_port_count{host=~\"$host\"}",
     "legendFormat": "Ports {{host}}"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "content": "This set of panels shows VM I/O.\n\n**VM IO**: rate of bytes transferred in and out the VM of the selected Host.\n\n**Ports**: the VM total open [ports](http://erlang.org/doc/reference_manual/ports.html) as well as the max ports available (dotted red line) if defined."
  }
 ]
}