{
 "title": "Networking: DNS",
 "description": "Metrics about dcos-dns",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(dns_forwarder_requests_duration_seconds_bucket, host)"
   },
   { "name": "rate_interval", "label": "Rate", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "dns_response_time_threshold",
    "label": "DNS Response Time Threshold (ms)",
    "query": "1,5,10,50,100,500,1000,5000"
   },
   { "name": "regex_dcos_zones", "label": "DC/OS DNS Zones", "query": "${VAR_REGEX_DCOS_ZONES}" }
  ]
 },
 "panels": [
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$dns_response_time_threshold/1000",
     "legendFormat": "Threshold"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dns_forwarder_requests_duration_seconds_bucket{host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dns_forwarder_requests_duration_seconds_bucket{host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dns_forwarder_requests_duration_seconds_bucket{host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dns_forwarder_requests_duration_seconds_bucket{host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(dns_forwarder_requests_duration_seconds_count{host=~\"$host\"}[$rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(dns_forwarder_failures_total{host=~\"$host\"}[$rate_interval])) > 0",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "DNS Response Time Help",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "content": "This panel shows some percentilies (`50th`, `90th`, `95th`, `99th`) for response time of `All` queries involving DNS. It also shows the number of requests per second `rps`.\n\nThe red dotted line shows the `DNS Response Time Threshold ($dns_response_time_threshold ms)`"
  },
  {
   "title": "DC/OS DNS Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$dns_response_time_threshold/1000",
     "legendFormat": "Threshold"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(dns_forwarder_requests_duration_seconds_count{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(dns_forwarder_failures_total{zone=~\"$regex_dcos_zones\", host=~\"$host\"}[$rate_interval])) > 0",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "DC/OS DNS Response Time",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "content": "This panel shows some percentilies (`50th`, `90th`, `95th`, `99th`) for response time of `dcos-dns` queries. It also shows the number of requests per second `rps`.\n\nThe red dotted line shows the `DNS Response Time Threshold ($dns_response_time_threshold ms)`"
  },
  {
   "title": "MesosDNS Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$dns_response_time_threshold/1000",
     "legendFormat": "Threshold"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=\"mesos.\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=\"mesos.\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=\"mesos.\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone=\"mesos.\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(dns_forwarder_requests_duration_seconds_count{zone=\"mesos.\", host=~\"$host\"}[$rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(dns_forwarder_failures_total{zone=\"mesos.\", host=~\"$host\"}[$rate_interval])) > 0",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Lorem ipsum dolor sit amet",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "content": "This panel shows some percentilies (`50th`, `90th`, `95th`, `99th`) for response time of `mesos-dns` queries. It also shows the number of requests per second `rps`.\n\nThe red dotted line shows the `DNS Response Time Threshold ($dns_response_time_threshold ms)`"
  },
  {
   "title": "Upstream DNS Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$dns_response_time_threshold/1000",
     "legendFormat": "Threshold"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dns_forwarder_requests_duration_seconds_bucket{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "sum(rate(dns_forwarder_requests_duration_seconds_count{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(dns_forwarder_failures_total{zone!~\"$regex_all_zones\", host=~\"$host\"}[$rate_interval])) > 0",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Upstream DNS Response Time",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "content": "This panel shows some percentilies (`50th`, `90th`, `95th`, `99th`) for response time of `usptream` queries. It also shows the number of requests per second `rps`.\n\nThe red dotted line shows the `DNS Response Time Threshold ($dns_response_time_threshold ms)`"
  },
  {
   "title": "DC/OS DNS Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    {
     "format": "short",
     "label": "DC/OS DNS Records on Leader Node"
    }
   ],
   "targets": [
    {
     "expr": "dns_zone_records{zone=\"dcos.thisdcos.directory.\", host=~\"$host\"} - scalar(dns_zone_records{zone=\"dcos.thisdcos.directory.\"} * on(host) group_left mesos_listener_is_leader > 0) != 0",
     "legendFormat": "Bars"
    },
    {
     "expr": "abs(dns_zone_records{zone=\"dcos.thisdcos.directory.\", host=~\"$host\"} - scalar(dns_zone_records{zone=\"dcos.thisdcos.directory.\", host=~\"$host\"} * on(host) group_left mesos_listener_is_leader > 0))",
     "legendFormat": "{{host}}"
    },
    { "expr": "0.5", "legendFormat": "Zero" },
    { "expr": "-0.5", "legendFormat": "Zero" },
    {
     "expr": "dns_zone_records{zone=\"dcos.thisdcos.directory.\"} * on (host) group_left mesos_listener_is_leader > 0",
     "legendFormat": "Total"
    },
    {
     "expr": "dns_zone_records{zone=\"dcos.thisdcos.directory.\"} * on (host) group_left mesos_listener_is_leader > 0",
     "legendFormat": "Total2"
    }
   ]
  },
  {
   "title": "DC/OS DNS node Records",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "content": "This panel shows the total number of `DNS Records` at the `leader` node as well as the delta for every other node in the cluster."
  },
  {
   "title": "DNS Response Time per Hosts",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dns_forwarder_requests_duration_seconds_bucket{host=~\"$host\"}[$rate_interval])) by (host, zone, le)) > $dns_response_time_threshold/1000"
    }
   ]
  },
  {
   "title": "DNS Response Time per Host Help",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "content": "This panel shows the 95th percentile response time for nodes where this value is above `DNS Response Time Threshold ($dns_response_time_threshold ms)`"
  },
  {
   "title": "DNS Errors per Host",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "ceil(sum(dns_forwarder_failures_total{host=~\"$host\"}) by (host, zone)) > 0"
    }
   ]
  },
  {
   "title": "DNS Errors per Host",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "content": "This panel shows the total number of failed DNS queries per `host`and `zone`."
  }
 ]
}