{
 "title": "Marathon: ZooKeeper",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "get (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_persistence_operations_get_duration_timer_seconds_p999{task_name=~\".+\"})",
     "legendFormat": "{{task_name}} p999"
    }
   ]
  },
  {
   "title": "delete (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_persistence_operations_delete_duration_timer_seconds_p999{task_name=~\".+\"})",
     "legendFormat": "{{task_name}} p999"
    }
   ]
  },
  {
   "title": "store (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_persistence_operations_store_duration_timer_seconds_p999{task_name=~\".+\"})",
     "legendFormat": "{{task_name}} p999"
    }
   ]
  },
  {
   "title": "versions (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_persistence_operations_versions_duration_timer_seconds_p999{task_name=~\".+\"})",
     "legendFormat": "{{task_name}} p999"
    }
   ]
  },
  {
   "title": "ids (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_persistence_operations_ids_duration_timer_seconds_p999{task_name=~\".+\"})",
     "legendFormat": "{{task_name}} p999"
    }
   ]
  }
 ]
}