{
 "title": "DC/OS MoM",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Interval", "query": "2m,5m,10m,30m,1h" },
   { "name": "mom_prefix", "query": "mom_apps" }
  ]
 },
 "panels": [
  {
   "title": "Active deployments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg([[mom_prefix]]_deployments_active_gauge)"
    }
   ]
  },
  {
   "title": "Active apps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_apps_active_gauge)"
    }
   ]
  },
  {
   "title": "Active pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_pods_active_gauge)"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_http_requests_duration_timer_seconds_p95)"
    }
   ]
  },
  {
   "title": "Leadership duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_leadership_duration_gauge_seconds)"
    }
   ]
  },
  {
   "title": "HTTP 2xx rpm",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "rpm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_http_responses_2xx_rate_meter_m1_rate) * 60"
    }
   ]
  },
  {
   "title": "HTTP response size rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(increase([[mom_prefix]]_http_responses_size_counter_bytes[10m]))"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max([[mom_prefix]]_jvm_memory_total_used_gauge_bytes)"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active applications running on root Marathon",
   "type": "graph",
   "description": "# Active applications on root Marathon\n\n## What does it mean\nThis metric shows the number of active applications in the root Marathon.\n\n## Expected behavior\nThe number should be relatively stable unless services are being actively deployed/removed.\n\n## Where to look when for further information:\nFollowing metrics can provide additional information:\n\n * `marathon_instances_running`\n * `marathon.instances_staged`\n * `marathon_mesos_offers`",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_apps_active_gauge)",
     "legendFormat": "Number of active apps on root Marathon"
    }
   ]
  },
  {
   "title": "Active pods running on root Marathon",
   "type": "graph",
   "description": "# Active pods on root Marathon\n\n## What does it mean\nThis metric shows the number of active pods in the root Marathon.\n\n## Expected behavior\nThe number should be relatively stable unless services are being actively deployed/removed.\n\n## Where to look when for further information:\nFollowing metrics can provide additional information:\n\n * `marathon_instances_running`\n * `marathon_instances_staged`\n * `marathon_mesos_offers`",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_pods_active_gauge)",
     "legendFormat": "Number of active pods on root Marathon"
    }
   ]
  },
  {
   "title": "Active deployments on root Marathon",
   "type": "graph",
   "description": "# Active deployments on root Marathon\n\n### What does it mean\nThis metric shows the number of active deployments in the root Marathon. \nA deployment happens when an app/pod was just created/updated and instances have to be started/killed. \n\n### Expected behavior\nThe number should usually be < 50, however, if the number of deployments is > 80 for a long period,\nthen it might be a signal that something is wrong.\n\n### Where to look when for further information:\nFollowing metrics can provide additional information:\n\n * `marathon_mesos_offers_incoming_counter`\n * `marathon_mesos_offers_declined_counter`\n * `marathon_mesos_offers_used_counter`\n * `marathon_mesos_calls_revive_counter`\n * `marathon_mesos_calls_suppress_counter`",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_deployments_active_gauge)",
     "legendFormat": "Number of active deployments on root Marathon"
    }
   ]
  },
  {
   "title": "Staged instances on root Marathon",
   "type": "graph",
   "description": "# Staged instances on root Marathon\n\n### What does it mean\nThis metric shows the number of staged instances in the root Marathon. An instance is staged when Marathon has sent a launch request to Mesos but it's not yet running.\n\n### Expected behavior\nThis metric shouldn't have a large value, one can expect it to be < 10, however sometimes it might reach high values. \nIf there are many staged instances, that might indicate a problem with an agent (docker daemon hangs, the image can't be pulled, etc.).\n\n### Where to look when for further information\nFollowing metrics can provide additional information:\n\n * `marathon_mesos_task_updates_task_error`\n * `marathon_mesos_task_updates_task_error_counter`",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_instances_staged_gauge)",
     "legendFormat": "Number of staged instances on root Marathon"
    }
   ]
  },
  {
   "title": "Running instances on root Marathon",
   "type": "graph",
   "description": "# Running instances on root Marathon\n\n### What does it mean\nThis metric shows the number of running instances in the root Marathon. \n\n### Expected behavior\nThis metric shouldn't have huge drops unless apps/pods being upscaled/downscaled.\n\n### Where to look when for further information:\nFollowing metrics can provide additional information:\n\n * `marathon_mesos_offers`",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_instances_running_gauge)",
     "legendFormat": "Number of running instances on root Marathon"
    }
   ]
  },
  {
   "title": "Launch overdue instances on root Marathon",
   "type": "graph",
   "description": "# Launch overdue instances on root Marathon\n\n### What does it mean\nThis metrics shows the number of overdue instances. Overdue instances are those that have been either launched or staged but hasn’t become running within the `task_launch_timeout` or `task_launch_confirm_timeout` respectively.\n\n### Expected behavior\nThis metric should be around 0 at all times. \n\n### Where to look when for further information\nThe next metrics can provide additional information:\n\n * `marathon_mesos_task_updates_task_error`\n * `marathon_mesos_task_updates_task_error_counter`",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max([[mom_prefix]]_instances_launch_overdue_gauge)",
     "legendFormat": "Number of overdue instances on root Marathon"
    }
   ]
  },
  {
   "title": "Marathon uptime and leader duration",
   "type": "graph",
   "description": "# Uptime and leadership duration of root Marathon masters\n\n### What does it mean\nThese metric shows the uptime of each root Marathon master and how long a given Marathon master stayed the leader.\n\n### Expected behavior\nThis value should be linearly increasing over time. If there is a drop, that means that Marathon was restarted. If there are multiple drops within a short period of time that can be a sign of instability. \nBoth, leadership duration and uptime should look the same since Marathon will restart upon leadership loss.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max by (host) ([[mom_prefix]]_uptime_gauge_seconds)",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "max by (host) ([[mom_prefix]]_leadership_duration_gauge_seconds)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Mesos Related Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Mesos offers overview",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Incoming offers\nOffers that marathon received from Mesos. If this value is low, then Marathon experiences an \"offer starvation\" unless a `suppress` call was issued.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_mesos_offers_incoming_counter[$min_interval])",
     "legendFormat": "Incoming offers"
    },
    {
     "expr": "increase([[mom_prefix]]_mesos_offers_declined_counter[$min_interval])",
     "legendFormat": "Declined offers"
    }
   ]
  },
  {
   "title": "Used Mesos offers",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Used offers\nThis metric shows the number of used Mesos offers. If Marathon is trying to deploy a service and receives enough incoming offers but doesn't seem to use any, then this usually means that the offers aren't a fit (bad role, not enough cpu/mem other resources, etc.)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_mesos_offers_used_counter[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Revive calls by root Marathon ($min_interval)",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Revive calls\nIf Marathon issues a `Revive` call, Mesos will start sending offers.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_mesos_calls_revive_counter[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Supress Mesos calls issued by root Marathon",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Suppress calls\nIf Marathon issues a `suppress` call, Mesos won't send any offers.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_mesos_calls_suppress_counter[$min_interval])",
     "legendFormat": "{{host}} ({{instance}})"
    }
   ]
  },
  { "title": "HTTP Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HTTP request duration p95",
   "type": "graph",
   "description": "# Marathon HTTP Metrics\n\n## Request duration\n\nThis metric shows 95 percentile request duration. High numbers mean that marathon is experiencing quite some load.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "[[mom_prefix]]_http_requests_duration_timer_seconds_p95",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP request size rate",
   "type": "graph",
   "description": "# Marathon HTTP Metrics\n\n## HTTP request size\n\nThese metrics show the size of Marathon requests. Too high values can lead to Marathon being overloaded with data serialization.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_http_requests_size_counter_bytes[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response size rate",
   "type": "graph",
   "description": "# Marathon HTTP Metrics\n\n## HTTP response size\n\nThese metrics show the size of Marathon responses. Too high values can lead to Marathon being overloaded with data serialization.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_http_responses_size_counter_bytes[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response 2xx rates",
   "type": "graph",
   "description": "# Marathon HTTP Metrics\n\n## HTTP response 2xx rates\n\nThis metric shows the rate of requests which resulted in status 200-299.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_http_responses_2xx_rate_meter_count[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response 5xx error rates",
   "type": "graph",
   "description": "# Marathon HTTP Metrics\n\n## HTTP response 5xx rates\n\nThis metric shows the rate of requests which resulted in status 500-599. A short period of 5xx responses is expected in situations such as leader re-election.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase([[mom_prefix]]_http_responses_5xx_rate_meter_count[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Marathon heap usage",
   "type": "graph",
   "description": "# Marathon JVM Metrics\n\n## Heap Usage\n\nThis metric shows Marathons heap usage. An overall growth pattern where more and more heap is being used can be an indication of a problem.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "[[mom_prefix]]_jvm_memory_heap_used_gauge_bytes",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Marathon total memory usage",
   "type": "graph",
   "description": "# Marathon JVM Metrics\n\n## Total Memory Usage\n\nThis metric shows total Marathons memory usage. An overall growth pattern where more and more heap is being used can be an indication of a problem.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "[[mom_prefix]]_jvm_memory_total_used_gauge_bytes",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Marathon active and runnable threads count",
   "type": "graph",
   "description": "# Marathon JVM Metrics\n\n## Active Thread Count\n\nThis metric total number of active (and runnable) threads used by Marathon. A sudden change in the number of threads can be an indication of a problem.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[mom_prefix]]_jvm_threads_active_gauge + [[mom_prefix]]_jvm_threads_runnable_gauge",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Marathon waiting and timed waiting threads count",
   "type": "graph",
   "description": "# Marathon JVM Metrics\n\n## Waiting Thread Count\n\nThis metric total number of waiting (and timed waiting) threads used by Marathon. A sudden change in the number of threads can be an indication of a problem.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "[[mom_prefix]]_jvm_threads_waiting_gauge + [[mom_prefix]]_jvm_threads_timed_waiting_gauge",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}