{
 "title": "Marathon: offers",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Launch op count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offer_operations_launch_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "LaunchGroup op count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offer_operations_launch_group_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Reserve op count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offer_operations_reserve_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Revive calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_calls_revive_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Used offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offers_used_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Declined offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offers_declined_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Queued offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_debug_offer_matcher_queue_size_gauge{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Incoming offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_offers_incoming_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Suppress calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (task_name) (marathon_mesos_calls_suppress_counter{task_name=~\".+\"})",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Incoming offers rate per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(marathon_mesos_offers_incoming_counter{task_name=~\".+\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}