{
 "title": "Mesos: Allocator Summary",
 "tags": [
  "dc/os",
  "mesos",
  "summary",
  "allocator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "metrics(mesos_allocator_mesos_allocation_run_ms)"
   }
  ]
 },
 "panels": [
  { "title": "Basic: [[percentile]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time spent in allocation algorithm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_ms[[percentile]]{state=\"leader\"}",
     "legendFormat": "$percentile"
    }
   ]
  },
  {
   "title": "Time spent in allocation algorithm",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "content": "Time spent in allocation algorithm.\n\nThe displayed metric shows the time spent for allocations as done by the Mesos master."
  },
  {
   "title": "# of allocation runs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_runs{state=\"leader\"}",
     "legendFormat": "Allocation Runs"
    }
   ]
  },
  {
   "title": "# of allocation runs",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "content": "Number of times the allocation algorithm has run.\n\nThe displayed value should continuously increase. A drop in the graph is a signal for the leading Mesos master to have become re-elected. Check the formally leading Mesos master unit log around the time of re-election for more details."
  },
  {
   "title": "Allocation batch latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_allocation_run_latency_ms[[percentile]]{state=\"leader\"}",
     "legendFormat": "$percentile"
    }
   ]
  },
  {
   "title": "Allocation batch latency",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "content": "Allocation batch latency.\n\nThis metric shows the delta between planned and actual allocations - large increases are a sign of the Mesos master allocator component being under increased load."
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_mesos_event_queue_dispatches{state=\"leader\"}",
     "legendFormat": "Dispatches"
    }
   ]
  },
  {
   "title": "Allocator dispatch queue length",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "content": "Allocator dispatch queue length.\n\nShows the number of dispatches in the allocator event queue - large increases are a sign of the Mesos master allocator component being under increased load which in turn can delay the deployment of new workload."
  }
 ]
}