{
 "title": "Mesos: Agents Summary",
 "description": "Show Mesos Agent metrics on a host",
 "tags": [
  "mesos",
  "agents",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mesos_slave_uptime_secs, instance)"
   },
   {
    "name": "rate",
    "label": "Rate Interval",
    "query": "1s,5s,10s,30s,1m,2m,5m,15m,30m,1h,2h,6h,1d,7d"
   }
  ]
 },
 "panels": [
  { "title": "Basic: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_uptime_secs{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mesos Agent Uptime",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "content": "Shows the time in seconds since the last restart of the Mesos agent(s).\n\nThese metrics should always increase. If one of the metrics drops to zero, the agent has restarted. \n\nFor analysing unplanned agent restarts further, check the Mesos agent node unit logs."
  },
  {
   "title": "Registered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_registered{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Registered",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "content": "Whether the agents are registered with a master.\n\nMesos agents should be registered with the Mesos master all of the time.\n\nAgents failing to register with the master are an unusual event that should get investigated further.\nThe Mesos agent unit log and the corresponding Mesos master unit log should help clearifying such failure - \nmake sure you consider both sides for validating results."
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_recovery_errors{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "On agent recovery"
    },
    {
     "expr": "sum(irate(mesos_slave_container_launch_errors{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "On container launch"
    },
    {
     "expr": "sum(irate(mesos_slave_invalid_status_updates{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "For status updates"
    },
    {
     "expr": "sum(irate(mesos_slave_invalid_framework_messages{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "For framework messages"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "content": "Number of errors encountered per second.\n\nIncreased error rates should be investigated by the operator - \nit is recommended to consult the Mesos agent unit log around and shortly before the time of increased error rates."
  },
  { "title": "Resources Summary: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "% of Allocated Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_cpus_used{instance=~\"$instance\"}) / sum(mesos_slave_cpus_total{instance=~\"$instance\"})",
     "legendFormat": "CPUs"
    },
    {
     "expr": "sum(mesos_slave_mem_used{instance=~\"$instance\"}) / sum(mesos_slave_mem_total{instance=~\"$instance\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(mesos_slave_disk_used{instance=~\"$instance\"}) / sum(mesos_slave_disk_total{instance=~\"$instance\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(mesos_slave_gpus_used{instance=~\"$instance\"}) / sum(mesos_slave_gpus_total{instance=~\"$instance\"})",
     "legendFormat": "GPUs"
    }
   ]
  },
  {
   "title": "% of Allocated Resources",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "content": "Percentage of resources allocated.\n\nThis graph shows the relation between total resources available and resources allocated."
  },
  { "title": "Resources Detailed: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_cpus_total{instance=~\"$instance\"} + mesos_slave_cpus_revocable_total{instance=~\"$instance\"})",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(mesos_slave_cpus_used{instance=~\"$instance\"})",
     "legendFormat": "Allocated CPUs"
    },
    {
     "expr": "sum(irate(cpus_system_time_secs{instance=~\"$instance\"}[$rate]) + irate(cpus_user_time_secs{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Containers CPU Usage"
    },
    {
     "expr": "sum(rate(cpus_system_time_secs{instance=~\"$instance\"}[$rate]) + rate(cpus_user_time_secs{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Containers CPU Usage Average"
    }
   ]
  },
  {
   "title": "CPU Allocation and Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "content": "Number of CPUs in total and allocated within the cluster. It additionally shows CPUs used by the container subsystem.\n\nThe amount of allocated CPUs does contain a subset of CPUs for executors. Mesos does allow for the executor part to go beyond the resource limits.\n\nThe container resource usage should be close to the allocation for better cluster utilization."
  },
  {
   "title": "Memory Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_mem_total{instance=~\"$instance\"} + mesos_slave_mem_revocable_total{instance=~\"$instance\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(mesos_slave_mem_used{instance=~\"$instance\"})",
     "legendFormat": "Offered or Allocated Memory"
    },
    {
     "expr": "sum(mem_total_bytes{instance=~\"$instance\"}) / 1000000",
     "legendFormat": "Containers Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Allocation and Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "content": "Memory in total and offered or allocated within the cluster. Additionally shows the amount of memory used by containers.\n\nThe amount of offered or allocated memory does contain a subset of memory for executors. Mesos does allow for the executor part to go beyond the resource limits."
  },
  {
   "title": "GPU Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_gpus_total{instance=~\"$instance\"} + mesos_slave_gpus_revocable_total{instance=~\"$instance\"})",
     "legendFormat": "Total GPUs"
    },
    {
     "expr": "sum(mesos_slave_gpus_used{instance=~\"$instance\"})",
     "legendFormat": "Offered or Allocated GPUs"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "content": "Number of GPUs in total and offered or allocated within the cluster."
  },
  {
   "title": "Disk Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_disk_total{instance=~\"$instance\"} + mesos_slave_disk_revocable_total{instance=~\"$instance\"})",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(mesos_slave_disk_used{instance=~\"$instance\"})",
     "legendFormat": "Offered of Allocated Disk"
    },
    {
     "expr": "sum(disk_used_bytes{instance=~\"$instance\"}) / 1000000",
     "legendFormat": "Container Disk Usage"
    }
   ]
  },
  {
   "title": "Disk Allocation",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
   "content": "Disk space in total and offered or allocated within the cluster. Additionally shows the amount of disk space used by containers."
  },
  { "title": "Executors: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Active Executors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_executors_registering{instance=~\"$instance\"})",
     "legendFormat": "Registering"
    },
    {
     "expr": "sum(mesos_slave_executors_running{instance=~\"$instance\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(mesos_slave_executors_terminating{instance=~\"$instance\"})",
     "legendFormat": "Terminating"
    }
   ]
  },
  {
   "title": "Active Executors",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 76 },
   "content": "Number of executors in an active state.\n\nExecutors should generally be in a *Running* state which should be dominating this graph, coupled to the amount of active tasks."
  },
  {
   "title": "Terminal Executors Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_executors_terminated{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(irate(mesos_slave_executors_preempted{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Preempted"
    }
   ]
  },
  {
   "title": "Terminal Executors Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 85 },
   "content": "Rate of executors terminated per second."
  },
  { "title": "Tasks: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_tasks_staging{instance=~\"$instance\"})",
     "legendFormat": "Staging"
    },
    {
     "expr": "sum(mesos_slave_tasks_starting{instance=~\"$instance\"})",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(mesos_slave_tasks_running{instance=~\"$instance\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(mesos_slave_tasks_killing{instance=~\"$instance\"})",
     "legendFormat": "Killing"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
   "content": "Number of tasks in an active state.\n\nThis graph should be predominantly showing tasks in *Running* state and, dependent on your workload, remain stable.\n\nTasks stuck in *Staging* or *Starting* for a long time should be investigated by looking at Mesos master and agent logs."
  },
  {
   "title": "Terminal Tasks Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_tasks_finished{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Finished"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_failed{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_gone{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Gone"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_killed{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Killed"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_lost{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "Terminal Tasks Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 104 },
   "content": "Rate of tasks terminated per second.\n\nFor short termed workload, this graph is expected to be dominated by tasks in *Finished* state. For long running services, under normal operation, we do not expect tasks in a terminal state.\n\nSpikes in anything but *Finished* or *Gone* state might indicate problems.\n"
  },
  { "title": "Mesos Agent Process: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "procstat_cpu_usage{process_name=\"mesos-agent\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Percent of Total CPU",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 114 },
   "content": "The percentage of time that the `mesos-agent` process is active in any capacity.\n\nThe displayed value is identical to what you would see if you used `ps` or `htop` and checked the results for the `mesos-agent` process.\n"
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "procstat_memory_rss{process_name=\"mesos-agent\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 123 },
   "content": "The amount of real memory (resident set) that the `mesos-agent` process is using.\n\nThe displayed value is identical to what you would see if you used `ps` or `htop` and checked the results for the `mesos-agent` process."
  }
 ]
}