{
 "title": "Mesos: Frameworks Summary",
 "tags": [
  "dc/os",
  "mesos",
  "frameworks",
  "summary"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "framework",
    "label": "Framework",
    "query": "label_values(mesos_master_frameworks_calls_total, framework_name)"
   },
   { "name": "rate", "label": "Rate Interval", "query": "2m,5m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  { "title": "Basic: $framework", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subscribed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_subscribed_total{framework_name=~\"$framework\"}",
     "legendFormat": "{{framework_name}}"
    }
   ]
  },
  {
   "title": "Framework subscribed",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "content": "Shows whether not the framework has an active subscription with the Mesos master.\n\nThis metric should commonly remain steady at 1. If the metric drops to zero, the framework may have restarted and some time of unavailability might be observed afterwards."
  },
  {
   "title": "Suppressing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_roles_suppressed{framework_name=~\"$framework\"}",
     "legendFormat": "{{framework_name}}: {{role_name}}"
    }
   ]
  },
  {
   "title": "Suppressing",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "content": "For each of the framework’s subscribed roles, whether or not offers for that role are currently suppressed.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Tasks: $framework", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_frameworks_tasks_active{framework_name=~\"$framework\"}) by (task_state)",
     "legendFormat": "{{task_state}}"
    }
   ]
  },
  {
   "title": "Count of active state tasks",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "content": "Shows count of tasks in an active state.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Terminal Tasks  Rate [$rate]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_master_frameworks_tasks_terminal{framework_name=~\"$framework\"}[$rate])) by (task_state)",
     "legendFormat": "{{task_state}}"
    }
   ]
  },
  {
   "title": "Count of terminal state tasks",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "content": "Shows count of tasks in a terminal state.\n\nTODO(tillt): Add expectation and interpretation hints. "
  },
  { "title": "Performance: $framework", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Offers Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mesos_master_frameworks_offers_sent{framework_name=~\"$framework\"}[$rate])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Rate of offers sent",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "content": "Shows rate of offers per second sent by the leading master.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Events Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_master_frameworks_events{framework_name=~\"$framework\"}[$rate])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Rate of events received",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "content": "This panel shows the rate of any kind of event received from the Mesos master.\n\nThis metric should commonly remain mostly flat and non-zero during normal framework operation.\n\nFor batch processing workloads, the rate might increase during load but should drop to its previous value after the operation is done. If operations are pending, but no offer events are observed, the service might be starved for resources. If this metric drops to zero, the service might have lost contact to the Mesos master and might need to be restarted."
  },
  {
   "title": "Calls Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_master_frameworks_calls{framework_name=~\"$framework\"}[$rate])) by (call_type)",
     "legendFormat": "{{call_type}}"
    }
   ]
  },
  {
   "title": "Rate of calls sent",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "content": "This panel shows the rate of any kind of call sent by the framework per second.\n\nThis metric should commonly remain mostly flat and non-zero during normal framework operation.\n\nFor batch processing workloads, the rate might increase during load but should drop to its previous value after the operation is done. If operations are pending, but no offer events are observed, the service might be starved for resources. If this metric drops to zero, the service might have lost contact to the Mesos master and might need to be restarted."
  }
 ]
}