{
 "title": "Mesos: Containers Summary",
 "description": "Actual CPU/Memory/Disk usage of your containers.",
 "tags": [
  "dc/os",
  "mesos",
  "container",
  "summary"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(cpus_system_time_secs, service_name)"
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\"}, task_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\"}, host)"
   },
   {
    "name": "container_id",
    "label": "Container ID",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\"}, container_id)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "2m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "CPU: $service | $task_name | $host | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpus_limit{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum(irate(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]) + irate(cpus_user_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "content": "Total percentage of CPU time spent by tasks of the cgroup combined in kernel and user mode.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cpus_nr_throttled{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]) / irate(cpus_nr_periods{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]))",
     "legendFormat": "CPU Throttle"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "content": "Rate of cgroup CPU throttle triggers, sampled over $rate_interval interval windows.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Memory: $service | $task_name | $host | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(mem_limit_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"})",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "sum(mem_total_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "content": "Memory size limit and memory used by container.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Disk:  $service | $task_name | $host | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_limit_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"})",
     "legendFormat": "Disk Limit"
    },
    {
     "expr": "sum(disk_used_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"})",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "content": "Disk space size limit and disk space used by container.\n\nTODO(tillt): Add expectation and interpretation hints. "
  },
  {
   "title": "Network: $service | $task_name | $host | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(net_rx_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(net_tx_bytes{service_name=~\"$service\", task_name=~\"$task_name\", host=~\"$host\", container_id=~\"$container_id\"}[$rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "content": "Bytes per second sent and received via network.\n\nTODO(tillt): Add expectation and interpretation hints."
  }
 ]
}