{
 "title": "Mesos: Masters Summary",
 "tags": [
  "mesos",
  "masters",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "rate", "label": "Rate Interval", "query": "1s,1m,2m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Master Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(mesos_master_uptime_secs) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mesos Master Uptime",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "content": "Shows the time in seconds since the last restart of the Mesos masters.\n\nThis metric should always increase. If the metric drops to zero, the master has restarted and a re-election might be observed afterwards.\n\nShort uptimes should be investigated as unplanned Mesos master restarts are considered unexpected."
  },
  {
   "title": "Leader Election",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mesos_master_elected", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mesos Master Leader Election",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "content": "Which master is elected leader.\n\nThere should always be a single Mesos master elected as leader. A leader election happens when the leading Master is restarted for planned maintenance (example Upgrades) or unplanned failures—these should be investigated.\n\nWhile investigating, try to look for patterns! \n\n- If there was a large gap of time where no Mesos master is elected leader\n- Leader election happening frequently (Mesos master flapping)\n- Several leading masters (Splitbrain situation)\n\nStart by looking at the previously leading (failed over) Mesos master unit log at around and before the time of the last re-election."
  },
  { "title": "Mesos Master Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "procstat_cpu_usage{process_name=\"mesos-master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Percent of Total CPUs",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "content": "The percentage of time that the `mesos-master` process is active in any capacity.\n\nThe displayed value is identical to what you would see if you used `ps` or `htop` and checked the results for the `mesos-master` process.\n\nUnder normal circumstances this graph is expected to remain relatively stable. Non leading masters will show low CPU use, only the leading master may show significant load. Unexpected spikes in CPU load are worth investigating.\n\nLook at correlated cluster events!\n\n- Mesos master leader re-election\n- Re-registration of framework or agents\n- Changes in task launch rate and lifetime\n- Increased rate of Mesos master endpoint requests"
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "procstat_memory_rss{process_name=\"mesos-master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "content": "The amount of real memory (resident set) that the process is using.\n\nThis graph should remain relatively stable and in close relation to the number of active tasks.\n\nBeyond conditions described in the **CPU Usage** paragraph, following constellations can lead to increased memory usage.\n\n- Slow reader attacks\n- Clients abandoning streaming connections without properly closing them\n- Mesos modules introducing resource leaks into the master process\n\nFor more general expectations and troubleshooting, see **CPU Usage** paragraph.\n"
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_event_queue_dispatches)",
     "legendFormat": "Dispatches"
    },
    {
     "expr": "sum(mesos_master_event_queue_http_requests)",
     "legendFormat": "HTTP Requests"
    },
    {
     "expr": "sum(mesos_master_event_queue_messages)",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "content": "Number of messages pending in the event queue of the actor associated with the Mesos master. These are the messages that are to be processed sequentially by a single thread.\nEach incoming HTTP API request adds to this queue size.\n\nTODO(tillt): Explain the upper bounds for explaining an expectation on normal mode.\n\nExceptionally large queue sizes may cause API timeouts. Optimize for reduced request frequency onto master endpoints or even entirely avoid them.\n\nThings to watch out for:\n- There are API endpoints which are known to be expensive on the Mesos master like `/state`\n- Re-registration of agents and/or frameworks\n\n\n"
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_tasks_staging{state=\"leader\"}",
     "legendFormat": "Staging"
    },
    {
     "expr": "mesos_master_tasks_starting{state=\"leader\"}",
     "legendFormat": "Starting"
    },
    {
     "expr": "mesos_master_tasks_running{state=\"leader\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "mesos_master_tasks_unreachable{state=\"leader\"}",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "content": "Number of tasks in active states.\n\nThis graph should be predominantly showing tasks in *Running* state and, dependent on your workload, remain stable.\n\nWhen seeing *Unreachable* tasks, the next step is confirming health of the agents. The next step would be looking at the [Mesos: Agents Summary](d/b7b4c454b/mesos-agents-summary) dashboard to investigate.\n\nTasks stuck in *Staging* or *Starting* for a long time should be investigated by looking at Mesos master and agent logs."
  },
  {
   "title": "Terminal Task Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mesos_master_tasks_finished{state=\"leader\"}[$rate])",
     "legendFormat": "Finished"
    },
    {
     "expr": "irate(mesos_master_tasks_failed{state=\"leader\"}[$rate])",
     "legendFormat": "Failed"
    },
    {
     "expr": "irate(mesos_master_tasks_gone{state=\"leader\"}[$rate])",
     "legendFormat": "Gone"
    },
    {
     "expr": "irate(mesos_master_tasks_gone_by_operator{state=\"leader\"}[$rate])",
     "legendFormat": "Gone by operator"
    },
    {
     "expr": "irate(mesos_master_tasks_dropped{state=\"leader\"}[$rate])",
     "legendFormat": "Dropped"
    },
    {
     "expr": "irate(mesos_master_tasks_killing{state=\"leader\"}[$rate])",
     "legendFormat": "Killing"
    },
    {
     "expr": "irate(mesos_master_tasks_killed{state=\"leader\"}[$rate])",
     "legendFormat": "Killed"
    },
    {
     "expr": "irate(mesos_master_tasks_lost{state=\"leader\"}[$rate])",
     "legendFormat": "Lost"
    },
    {
     "expr": "irate(mesos_master_tasks_error{state=\"leader\"}[$rate])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Terminal Task Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "content": "Tasks per second reaching a terminal state.\n\nFor short termed workload, this graph is expected to be dominated by tasks in *Finished* state. For long running services, under normal operation, we do not expect tasks in a terminal state.\n\nSpikes in anything but *Finished* state might indicate problems.\n"
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Number of Frameworks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_frameworks_connected{state=\"leader\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mesos_master_frameworks_disconnected{state=\"leader\"}",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "mesos_master_frameworks_active{state=\"leader\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "mesos_master_frameworks_inactive{state=\"leader\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Number of Frameworks",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "content": "Number of frameworks.\n\nThis metric is expected to remain steady and dominated by *Connected* and *Active* frameworks whereas both values are expected to be equal. \n\nWhen there are unplanned framework disconnects, the next step would be looking at the [Mesos: Frameworks Summary](d/C3EFGTeiz/mesos-frameworks-summary) dashboard to investigate."
  },
  {
   "title": "Number of Agents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_slaves_connected{state=\"leader\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mesos_master_slaves_disconnected{state=\"leader\"}",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "mesos_master_slaves_active{state=\"leader\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "mesos_master_slaves_inactive{state=\"leader\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "mesos_master_slaves_unreachable{state=\"leader\"}",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Number of Agents",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 76 },
   "content": "Number of Mesos agents.\n\nThis metric is expected to remain steady and dominated by *Connected* and *Active* agents whereas both values are expected to be equal. \n\nWhen unplanned agent disconnects are visible, the next step can be looking at the [Mesos: Agents Summary](d/b7b4c454b/mesos-agents-summary) dashboard and see if by looking at the up-time of all agents the failing nodes can be identified for further inspection."
  }
 ]
}