{
 "title": "Mesosphere DC/OS Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_cpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "avg(max by(instance)(cpu_usage_system{dcos_cluster_name=\"$clustername\"} + cpu_usage_user{dcos_cluster_name=\"$clustername\"} + cpu_usage_guest{dcos_cluster_name=\"$clustername\"}) / 100)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (host) (mem_used{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(sum by (host) (mem_rss_bytes{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "More Detail", "type": "dashlist", "gridPos": { "h": 24, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_disk_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_gpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Running Workload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_frameworks_connected{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "count(count by(task_name) (cpus_limit{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Tasks"
    },
    {
     "expr": "count(count by(container_id) (cpus_limit{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Connected Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(system_uptime{job=\"master-metrics\"})",
     "legendFormat": "Masters"
    },
    {
     "expr": "count(system_uptime{job=\"agent-metrics\"})",
     "legendFormat": "Agents"
    }
   ]
  }
 ]
}