{
 "title": "/Mesos-Container-Details",
 "description": "Actual CPU/Memory/Disk usage of your containers.",
 "tags": [
  "dc/os",
  "mesos",
  "detail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "query": "label_values(service_name)" },
   { "name": "executor_name", "query": "label_values(executor_name)" },
   { "name": "task_name", "query": "label_values(task_name)" },
   { "name": "rate_interval", "query": "2m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}",
     "legendFormat": "CPU Limit (container {{container_id}}, {{host}})"
    },
    {
     "expr": "rate(cpus_system_time_secs{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval]) + rate(cpus_user_time_secs{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval])",
     "legendFormat": "CPU Usage (container {{container_id}}, {{host}})"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(cpus_nr_throttled{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval]) / rate(cpus_nr_periods{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval]) * 100",
     "legendFormat": "(container {{container_id}}, {{host}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_limit_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}",
     "legendFormat": "Memory Limit (container {{container_id}}, {{host}})"
    },
    {
     "expr": "mem_total_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}",
     "legendFormat": "Memory Usage (container {{container_id}}, {{host}})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_limit_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}",
     "legendFormat": "Disk Limit (container {{container_id}}, {{host}})"
    },
    {
     "expr": "disk_used_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}",
     "legendFormat": "Disk Usage (container {{container_id}}, {{host}})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(net_rx_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval])",
     "legendFormat": "Recv (container {{container_id}}, {{host}})"
    },
    {
     "expr": "rate(net_tx_bytes{service_name=~\"$service_name\",executor_name=~\"$executor_name\",task_name=~\"$task_name\"}[$rate_interval])",
     "legendFormat": "Sent (container {{container_id}}, {{host}})"
    }
   ]
  }
 ]
}