{
 "title": "Mesos: Container Details",
 "description": "Actual CPU/Memory/Disk usage of your containers.",
 "tags": [
  "dc/os",
  "mesos",
  "detail",
  "container"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(cpus_system_time_secs, service_name)"
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\"}, task_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\"}, instance)"
   },
   {
    "name": "container_id",
    "label": "Container ID",
    "query": "label_values(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\"}, container_id)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "2m" }
  ]
 },
 "panels": [
  {
   "title": "CPU: $service | $task_name | $instance | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}",
     "legendFormat": "CPU Limit ({{container_id}})"
    },
    {
     "expr": "sum(irate(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval]) + irate(cpus_user_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval]))",
     "legendFormat": "CPU Usage ({{container_id}})"
    },
    {
     "expr": "rate(cpus_system_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval]) + rate(cpus_user_time_secs{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval])",
     "legendFormat": "CPU Usage Average ({{container_id}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "content": "Total CPUs used.\n\nShows the number of CPUs used by the container subsystem.\n\nThe container resource usage should be close to the allocation for better cluster utilization."
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(cpus_nr_throttled{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval]) / irate(cpus_nr_periods{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval])",
     "legendFormat": "CPU Throttle ({{container_id}})"
    }
   ]
  },
  { "title": "CPU Throttling", "type": "text", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 }, "content": "CGroup CPU throttle triggers." },
  {
   "title": "Memory: $service | $task_name | $instance | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_limit_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}",
     "legendFormat": "Memory Limit ({{container_id}})"
    },
    {
     "expr": "mem_total_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}",
     "legendFormat": "Memory Usage ({{container_id}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "content": "Memory size limit and memory used by container.\n\nContainers exceeding their memory limit may get OOM killed."
  },
  {
   "title": "Disk:  $service | $task_name | $instance | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_limit_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}",
     "legendFormat": "Disk Limit ({{container_id}})"
    },
    {
     "expr": "disk_used_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}",
     "legendFormat": "Disk Usage ({{container_id}})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "content": "Disk space size limit and disk space used by container.\n"
  },
  {
   "title": "Network: $service | $task_name | $instance | $container_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(net_rx_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval])",
     "legendFormat": "Received ({{container_id}})"
    },
    {
     "expr": "irate(net_tx_bytes{service_name=~\"$service\", task_name=~\"$task_name\", instance=~\"$instance\", container_id=~\"$container_id\"}[$rate_interval])",
     "legendFormat": "Sent ({{container_id}})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "content": "Bytes per second sent and received via network."
  }
 ]
}