{
 "title": "Metronome: Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "Interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Active job runs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(metronome_jobs_active_gauge)"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(metronome_http_requests_duration_timer_seconds_p95)"
    }
   ]
  },
  {
   "title": "Leadership duration",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(metronome_leadership_duration_gauge_seconds)"
    }
   ]
  },
  {
   "title": "HTTP 2xx rpm",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "rpm",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(metronome_http_responses_2xx_rate_counter[$min_interval])"
    }
   ]
  },
  {
   "title": "HTTP response size rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(increase(metronome_http_responses_size_counter_bytes[$min_interval]))"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(metronome_jvm_memory_total_used_gauge_bytes)"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active/failed job runs",
   "type": "graph",
   "description": "# Job runs overview\n\n## What does it mean\nThis metric shows the number of active and failed job runs in Metronome over time.\n\n## Expected behavior\nNumber of failed jobs should be zero at all times. In terms of active runs, the shape of the graph strongly depends on what schedule your jobs run on so it will differ in various clusters.\n\n## Where to look when for further information:\nThe next metrics can provide additional information:\n\n * `metronome_jobs_started`",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(metronome_jobs_active_gauge)",
     "legendFormat": "active"
    },
    {
     "expr": "max(metronome_jobs_failed_gauge)",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Staged job runs",
   "type": "graph",
   "description": "# Staged job runs\n\n### What does it mean\nNumber of staged job runs is count of jobs that we already requested to start in mesos but they did not turn running yet.\n\n### Expected behavior\nNumber of staged jobs should be roughly equal to number of job runs started in that time period. If this value is growing or have high value it might indicate a problem with an agent (docker daemon hangs, image can't be pulled, etc.).\n\n### Where to look when for further information\nThe next metrics can provide additional information:\n\n * `metronome_mesos_task_updates_task_error`\n * `metronome_mesos_task_updates_task_error_counter`",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(metronome_instances_staged_gauge)",
     "legendFormat": "staged"
    }
   ]
  },
  {
   "title": "Launch overdue job runs",
   "type": "graph",
   "description": "# Launch overdue job runs\n\n### What does it mean\nOverdue jobs are those that we already accepted offer for but they haven’t become running within the `METRONOME_SCHEDULER_TASK_LAUNCH_TIMEOUT` or `METRONOME_SCHEDULER_TASK_LAUNCH_CONFIRM_TIMEOUT` respectively.\n\n### Expected behavior\nValue of this should be 0 at all times. \n\n### Where to look when for further information\nThe next metrics can provide additional information:\n\n * `metronome_mesos_task_updates_task_error`\n * `metronome_mesos_task_updates_task_error_counter`",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(metronome_instances_launch_overdue_gauge)",
     "legendFormat": "overdue"
    }
   ]
  },
  {
   "title": "Uptime and leader duration",
   "type": "graph",
   "description": "# Leardship duration of master nodes\n\n### What does it mean\nIt shows which master node is a leader and how long is the leadership period.\n\n### Expected behavior\nThis value should be linearly increasing over time. If a leader is being re-elected frequently (short leadership duration) that can be a sign of instability. Node can lose leadership e.g. because of lost connection to zookeeper, mesos or because of some other unrecoverable error.",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max by (host) (metronome_leadership_duration_gauge_seconds)",
     "legendFormat": "leadership {{host}}"
    },
    {
     "expr": "max by (host) (metronome_uptime_gauge_seconds)",
     "legendFormat": "uptime {{host}}"
    }
   ]
  },
  { "title": "Mesos Related Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Mesos offers overview",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Declined offers\nOffers that were declined by Marathon. If that value is high than \n\n### Incoming offers\nOffers that marathon received from Mesos. If this value is low, then Marathon is starving unless a `supress` call was issued.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_mesos_offers_declined_counter[$min_interval])",
     "legendFormat": "declined"
    },
    {
     "expr": "increase(metronome_mesos_offers_incoming_counter[$min_interval])",
     "legendFormat": "incoming"
    }
   ]
  },
  {
   "title": "Used mesos offers",
   "type": "graph",
   "description": "# Mesos offers metrics\n\n### Used offers\nThis metric shows the number of used Mesos offers. If Metronome is trying to deploy a service and receives enough incoming offers but doesn't seem to use any, then this usually means that the offers aren't a fit (bad role, not enough cpu/mem other resources, etc.)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_mesos_offers_used_counter[$min_interval])",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Supress/Revive Mesos calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_mesos_calls_suppress_counter[$min_interval])",
     "legendFormat": "suppress"
    },
    {
     "expr": "increase(metronome_mesos_calls_suppress_counter[$min_interval])",
     "legendFormat": "revive"
    }
   ]
  },
  { "title": "HTTP Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP request duration p95",
   "type": "graph",
   "description": "This metric shows 95 percentile response latency. High numbers mean that marathon is experiencing quite some load.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "metronome_http_requests_duration_timer_seconds_p95",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP request size rate",
   "type": "graph",
   "description": "These metrics show the size of Marathon requests. Too high values can lead to Marathon being overloaded with data serialization.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_http_requests_size_counter_bytes[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response size rate",
   "type": "graph",
   "description": "These metrics show the size of Marathon responses. Too high values can lead to Marathon being overloaded with data serialization.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_http_responses_size_counter_bytes[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response 2xx rates",
   "type": "graph",
   "description": "This metric shows the rate of requests with resulted in status 200-299.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_http_responses_2xx_rate_counter[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "HTTP response 5xx error rates",
   "type": "graph",
   "description": "This metric shows the rate of requests with resulted in status 500-599. A small amount of such responses are expected in some situations, such as leader re-election.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(metronome_http_responses_5xx_rate_counter[$min_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Heap usage",
   "type": "graph",
   "description": "An overall growing pattern where more and more heap is being used can be an indication of a problem.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "metronome_jvm_memory_heap_used_gauge_bytes",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active and runnable threads count",
   "type": "graph",
   "description": "A sudden change in number of threads can be an indication of a problem. Also having too many threads may be an indication of possible performance issues.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metronome_jvm_threads_active_gauge + metronome_jvm_threads_runnable_gauge",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "description": "An overall growing pattern where more and more memory is being used can be an indication of a problem.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "metronome_jvm_memory_total_used_gauge_bytes",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Marathon waiting and timed waiting threads count",
   "type": "graph",
   "description": "A sudden change in number of threads can be an indication of a problem.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metronome_jvm_threads_waiting_gauge + metronome_jvm_threads_timed_waiting_gauge",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}