{
 "title": "DC/OS Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_master_frameworks_connected{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "count(count by(task_name) (cpus_limit{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Tasks"
    },
    {
     "expr": "count(count by(container_id) (cpus_limit{dcos_cluster_name=\"$clustername\"}))",
     "legendFormat": "Containers"
    }
   ]
  },
  { "title": "More Detail", "type": "dashlist", "gridPos": { "h": 18, "w": 9, "x": 15, "y": 0 } },
  {
   "title": "Allocated Resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_cpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "CPUs"
    },
    {
     "expr": "avg(mesos_slave_mem_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "avg(mesos_slave_disk_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "avg(mesos_slave_gpus_percent{dcos_cluster_name=\"$clustername\"})",
     "legendFormat": "GPUs"
    }
   ]
  },
  {
   "title": "Connected Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(system_uptime{job=\"master-metrics\"})",
     "legendFormat": "Masters"
    },
    {
     "expr": "count(system_uptime{job=\"agent-metrics\"})",
     "legendFormat": "Agents"
    }
   ]
  }
 ]
}