{
 "title": "/Storage-Details",
 "tags": [
  "dc/os",
  "storage",
  "detail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DSS/Mesos GET_AGENTS pXX (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_master_calls_get_agents_process_p50"
    },
    {
     "expr": "dss_master_calls_get_agents_process_p75"
    },
    {
     "expr": "dss_master_calls_get_agents_process_p95"
    },
    {
     "expr": "dss_master_calls_get_agents_process_p99"
    },
    {
     "expr": "dss_master_calls_get_agents_process_p999"
    }
   ]
  },
  {
   "title": "DSS/Mesos Agent v1 API pXX (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_agent_calls_add_resource_provider_config_process_p99"
    },
    {
     "expr": "dss_agent_calls_add_resource_provider_config_process_p999"
    },
    {
     "expr": "dss_agent_calls_remove_resource_provider_config_process_p99"
    },
    {
     "expr": "dss_agent_calls_remove_resource_provider_config_process_p999"
    },
    {
     "expr": "dss_agent_calls_get_resource_providers_process_p99"
    },
    {
     "expr": "dss_agent_calls_get_resource_providers_process_p999"
    }
   ]
  },
  {
   "title": "DSS Offer Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_sched_events_offers_m1_rate"
    },
    {
     "expr": "dss_sched_events_offers_m5_rate"
    },
    {
     "expr": "dss_sched_events_offers_m15_rate"
    }
   ]
  },
  {
   "title": "Storage offer filter counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_allocator_offer_filters_roles_active{role=\"dcos-storage\"}",
     "legendFormat": "dcos-storage"
    },
    {
     "expr": "mesos_allocator_offer_filters_roles_active{role=\"dcos-storage/claimed\"}",
     "legendFormat": "dcos-storage/claimed"
    }
   ]
  },
  {
   "title": "DSS Revive Throttle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_sched_calls_revive_throttle_p50"
    },
    {
     "expr": "dss_sched_calls_revive_throttle_p75"
    },
    {
     "expr": "dss_sched_calls_revive_throttle_p95"
    },
    {
     "expr": "dss_sched_calls_revive_throttle_p99"
    },
    {
     "expr": "dss_sched_calls_revive_throttle_p999"
    }
   ]
  },
  {
   "title": "DSS Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_go_rt_goroutines" }
   ]
  },
  {
   "title": "DSS Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_go_mm_heap_inuse" },
    { "expr": "dss_go_mm_stack_inuse" },
    { "expr": "dss_go_mm_mspan_inuse" },
    { "expr": "dss_go_mm_mcache_sys" },
    { "expr": "dss_go_mm_buck_hash_sys" },
    { "expr": "dss_go_mm_gc_sys" },
    { "expr": "dss_go_mm_other_sys" }
   ]
  },
  {
   "title": "Arbiter Reconciliation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dss_sched_calls_reconcile_ops_throttled[5m])"
    },
    { "expr": "dss_arbiter_reconcile_m1_rate" },
    { "expr": "dss_arbiter_reconcile_m5_rate" },
    { "expr": "dss_arbiter_reconcile_m15_rate" },
    {
     "expr": "rate(dss_sched_calls_reconcile_ops_dropped[5m])"
    }
   ]
  },
  {
   "title": "DSS Arbiter Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_arbiter_dev_claim_len" },
    { "expr": "dss_arbiter_dev_unclaim_len" },
    { "expr": "dss_arbiter_lv_create_len" },
    { "expr": "dss_arbiter_lv_remove_len" }
   ]
  },
  {
   "title": "DSS Arbiter Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_arbiter_dev_claim_err" },
    { "expr": "dss_arbiter_dev_unclaim_err" },
    { "expr": "dss_arbiter_lv_create_err" },
    { "expr": "dss_arbiter_lv_remove_err" }
   ]
  },
  {
   "title": "GET rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dss_http_get_2xx_process_count[5m])",
     "legendFormat": "2xx rate"
    },
    {
     "expr": "rate(dss_http_get_4xx_process_count[5m])",
     "legendFormat": "4xx rate"
    }
   ]
  },
  {
   "title": "HTTP Requests (1m)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    { "expr": "dss_http_requests_m1_rate" }
   ]
  },
  {
   "title": "HTTP Connection Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dss_http_conn_err_m1_rate" },
    { "expr": "dss_http_conn_err_m5_rate" },
    { "expr": "dss_http_conn_err_m15_rate" }
   ]
  },
  {
   "title": "DSS List Targets pXX (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_grpc_api_Targets_ListTargets_ok_process_p99"
    },
    {
     "expr": "dss_grpc_api_Targets_ListTargets_ok_process_p999"
    }
   ]
  },
  {
   "title": "TargetGetCapabilities RPC (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dss_grpc_api_TargetCapabilities_TargetGetCapabilities_ok_process_m1_rate"
    }
   ]
  }
 ]
}