{
 "title": "Telegraf: Agent",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(internal_agent_metrics_gathered, host)"
   },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Gather Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_gathered{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Gather Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_gathered{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_written{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_written{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_dropped{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(internal_agent_metrics_dropped{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Gather Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(internal_agent_gather_errors{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Gather Error Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "rate(internal_agent_gather_errors{host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}