{
 "title": "/Telegraf/Output",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(internal_agent_metrics_gathered, host)"
   },
   {
    "name": "plugin",
    "label": "Plugin",
    "query": "label_values(internal_write_metrics_written, output)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(internal_write_metrics_written{host=~\"$node\", output=~\"$plugin\"}[$rate_interval])) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(internal_write_metrics_written{host=~\"$node\", output=~\"$plugin\"}[$rate_interval])) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Filter Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(internal_write_metrics_filtered{host=~\"$node\", output=~\"$plugin\"}[$rate_interval])) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Filter Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(internal_write_metrics_filtered{host=~\"$node\", output=~\"$plugin\"}[$rate_interval])) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Write Duration: 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "quantile(0.90, internal_write_write_time_ns{host=~\"$node\", output=~\"$plugin\"}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Write Duration: Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(internal_write_write_time_ns{host=~\"$node\", output=~\"$plugin\"}) by (output)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "internal_write_buffer_size{host=~\"$node\", output=~\"$plugin\"}",
     "legendFormat": "{{host}} | {{output}}"
    }
   ]
  }
 ]
}