{
 "title": "Telegraf: Input",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(internal_agent_metrics_gathered, host)"
   },
   {
    "name": "plugin",
    "label": "Plugin",
    "query": "label_values(internal_gather_metrics_gathered, input)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Gather Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(internal_gather_metrics_gathered{host=~\"$node\", input=~\"$plugin\"}[$rate_interval])) by (input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "Gather Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(internal_gather_metrics_gathered{host=~\"$node\", input=~\"$plugin\"}[$rate_interval])) by (input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "Gather Duration: 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "quantile(0.90, internal_gather_gather_time_ns{host=~\"$node\", input=~\"$plugin\"}) by (input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "Gather Duration: Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(internal_gather_gather_time_ns{host=~\"$node\", input=~\"$plugin\"}) by (input)",
     "legendFormat": "{{input}}"
    }
   ]
  }
 ]
}