{
 "title": "ZooKeeper: Summary",
 "tags": [
  "dc/os",
  "summary",
  "zookeeper"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(zookeeper_avg_latency{dcos_component_name=\"ZooKeeper\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Average Latency: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "zookeeper_avg_latency{dcos_component_name=\"ZooKeeper\", host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Average Latency",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "content": "Average latency for communication between ZooKeeper nodes measured in ticks. One tick is the configurable time unit used by ZooKeeper. In the context of DC/OS one ZooKeeper tick corresponds to 2000 milliseconds. An average latency beyond 10 ticks should be considered critical."
  },
  {
   "title": "Outstanding Requests: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_outstanding_requests{dcos_component_name=\"ZooKeeper\", host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Outstanding Requests",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "content": "Number of outstanding requests towards the ZooKeeper quorum. Clients can submit requests faster than ZooKeeper can process them. To prevent ZooKeeper from running out of memory due to queued requests, ZooKeeper will throttle clients so that there are no more than 1000 outstanding requests in the system."
  },
  {
   "title": "Fsync Threshold Exceed Count: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_fsync_threshold_exceed_count{dcos_component_name=\"ZooKeeper\", host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Fsync Threshold Exceed Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "content": "Number of times for fsync threshold exceeded. ZooKeeper completes fsync of new transactions to the write ahead log before any update takes place, and before sending a response back to the client. Slow fsync for transaction log is one of the most common reasons for slow ZooKeeper response times."
  },
  {
   "title": "Data Size: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zookeeper_approximate_data_size{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Data Size",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Approximation of data stored in the ZooKeeper namespace."
  },
  {
   "title": "Znode Count: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_znode_count{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Znode Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "content": "Number of Znodes in the ZooKeeper namespace."
  },
  {
   "title": "Ephemeral Znode Count: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_ephemerals_count{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Ephemeral Znode Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "content": "Ephemeral Znode Count. Ephemeral Znodes exist as long as the session that created the Znodes is active. When the session ends the Znodes are deleted."
  },
  {
   "title": "Watch count: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_watch_count{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Watch Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "content": "Number of watchers setup over Znodes."
  },
  {
   "title": "Number of alive connections: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zookeeper_num_alive_connections{dcos_component_name=\"ZooKeeper\", host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Number Alive Connections",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "content": "Number of alive connections per ZooKeeper instance."
  },
  {
   "title": "Packet Send Rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_packets_sent{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Packet Send Rate",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "content": "Rate of packets being sent per ZooKeeper instance."
  },
  {
   "title": "Packet Receive Rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_packets_received{dcos_component_name=\"ZooKeeper\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Packet Receive Rate",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "content": "Rate of packets being received per ZooKeeper instance."
  }
 ]
}