{
 "title": "/dcos-generic/dashboards/Secrets/Vault/Vault-Details",
 "tags": [
  "dc/os",
  "summary",
  "vault",
  "secrets"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(zookeeper_avg_latency{dcos_component_name=\"ZooKeeper\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Vault: Barrier GET operations count",
   "type": "graph",
   "description": "Number of GET operations at Vault Barrier",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_get_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier GET operations count",
   "type": "text",
   "description": "Number of GET operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "content": "Number of GET operations ar Vault Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Barrier GET operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by GET operations at the Barrier.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_get_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier GET operation duration, 90th percentile",
   "type": "text",
   "description": "Duration of time taken by GET operations at the Barrier",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "content": "Duration of time taken by GET operations at the Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Barrier PUT operations count",
   "type": "graph",
   "description": "Number of PUT operations at Vault Barrier",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_put_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier PUT operations count",
   "type": "text",
   "description": "Number of PUT operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "content": "Number of PUT operations ar Vault Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Barrier PUT operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by PUT operations at the Barrier.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_put_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier PUT operation duration, 90th percentile",
   "type": "text",
   "description": "Duration of time taken by PUT operations at the Barrier",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Duration of time taken by PUT operations at the Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Barrier DELETE operations count",
   "type": "graph",
   "description": "Number of DELETE operations at Vault Barrier",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_delete_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier DELETE operations count",
   "type": "text",
   "description": "Number of DELETE operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "content": "Number of DELETE operations ar Vault Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Barrier DELETE operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by DELETE operations at the Barrier.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_barrier_delete_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Barrier DELETE operation duration, 90th percentile",
   "type": "text",
   "description": "Duration of time taken by DELETE operations at the Barrier",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "content": "Duration of time taken by DELETE operations at the Barrier. For details on Vault Barrier, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Audit log request and response count",
   "type": "graph",
   "description": "Number of all audit log requests and responses across all audit log devices.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vault_audit_log_request_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "vault_audit_log_response_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Audit log request and response count",
   "type": "text",
   "description": "Number of all audit log requests and responses across all audit log devices.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "content": "Number of all audit log requests and responses across all audit log devices. For details on audit procedure, see [Vault Documentation](https://www.vaultproject.io/docs/audit/index.html)"
  },
  {
   "title": "Vault: Audit log request and response duration, 90th percentile",
   "type": "graph",
   "description": "Time duration (in milliseconds) of all audit log requests across all audit log devices.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_audit_log_request_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "vault_audit_log_response_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Audit log request and response duration, 90th percentile",
   "type": "text",
   "description": "Number of all audit log requests and responses across all audit log devices.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "content": "Time duration (in milliseconds) of all audit log requests and responses across all audit log devices. For details on audit procedure, see [Vault Documentation](https://www.vaultproject.io/docs/audit/index.html)"
  },
  {
   "title": "Vault: Policy fetching time, 90th percentile",
   "type": "graph",
   "description": "Time (in milliseconds) taken to get a policy.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_policy_get_policy_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Policy fetching time, 90th percentile",
   "type": "text",
   "description": "Time (in milliseconds) taken to get a policy.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "content": "Time (in milliseconds) taken to get a policy. For details on policies, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault core: Token lookup duration, 90th percentile",
   "type": "graph",
   "description": "The time (in milliseconds) taken to look up a token.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_token_lookup_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault core: Token lookup duration, 90th percentile",
   "type": "text",
   "description": "The time (in milliseconds) taken to look up a token.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "content": "The time (in milliseconds) taken to look up a token. For details on Vault architecture, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault core: Token checks duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by token checks handled by Vault core.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_check_token_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault core: Token checks duration, 90th percentile",
   "type": "text",
   "description": "Duration of time (in milliseconds) taken by token checks handled by Vault core.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "content": "Duration of time (in milliseconds) taken by token checks handled by Vault core. For details on Vault architecture, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault core: ACL and corresponding token entry fetch duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by ACL and corresponding token entry fetches handled by Vault core.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_fetch_acl_and_token_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault core: ACL and corresponding token entry fetch duration, 90th percentile",
   "type": "text",
   "description": "Duration of time (in milliseconds) taken by ACL and corresponding token entry fetches handled by Vault core.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "content": "Duration of time (in milliseconds) taken by ACL and corresponding token entry fetches handled by Vault core. For details on Vault architecture, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault core: Request handling duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken by requests handled by Vault core.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_request_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault core: Request handling duration, 90th percentile",
   "type": "text",
   "description": "Duration of time (in milliseconds) taken by requests handled by Vault core.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "content": "Duration of time (in milliseconds) taken by requests handled by Vault core. For details on Vault architecture, see [Vault Documentation](https://www.vaultproject.io/docs/internals/architecture.html)"
  },
  {
   "title": "Vault: Rollback operations duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken to perform a rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_rollback_attempt_secret__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - K/V secret bakcend"
    },
    {
     "expr": "vault_rollback_attempt_cubbyhole__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - Cubbyhole secret bakcend"
    },
    {
     "expr": "vault_rollback_attempt_sys__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - System bakcend"
    }
   ]
  },
  {
   "title": "Vault: Rollback operations duration, 90th percentile",
   "type": "text",
   "description": "Duration of time (in milliseconds) taken to perform a rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 91 },
   "content": "Duration of time (in milliseconds) taken to perform a rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.\n\nFor details on K/V Secrets Engine, check [Vault Documentation](https://www.vaultproject.io/docs/secrets/kv/index.html)\n\nFor details on Cubbyhole Secrets Engine, check [Vault Documentation](https://www.vaultproject.io/docs/secrets/cubbyhole/index.html)"
  },
  {
   "title": "Vault: Route rollback operations duration, 90th percentile",
   "type": "graph",
   "description": "Duration of time (in milliseconds) taken to perform a route rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_route_rollback_secret__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - K/V secret bakcend"
    },
    {
     "expr": "vault_route_rollback_cubbyhole__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - Cubbyhole secret bakcend"
    },
    {
     "expr": "vault_route_rollback_sys__90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}} - System bakcend"
    }
   ]
  },
  {
   "title": "Vault: Route rollback operations duration, 90th percentile",
   "type": "text",
   "description": "Duration of time (in milliseconds) taken to perform a route rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
   "content": "Duration of time (in milliseconds) taken to perform a route rollback operation for the K/V secret backend, Cubbyhole secret backend and system backend.\n\nFor details on K/V Secrets Engine, check [Vault Documentation](https://www.vaultproject.io/docs/secrets/kv/index.html)\n\nFor details on Cubbyhole Secrets Engine, check [Vault Documentation](https://www.vaultproject.io/docs/secrets/cubbyhole/index.html)"
  }
 ]
}