{
 "title": "/dcos-generic/dashboards/Secrets/Vault/Vault-Summary",
 "tags": [
  "dc/os",
  "summary",
  "vault",
  "secrets"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(zookeeper_avg_latency{dcos_component_name=\"ZooKeeper\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Vault: ZooKeeper GET operations count",
   "type": "graph",
   "description": "Number of GET operations on ZooKeeper by Vault",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_get_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Zookeeper GET operations count",
   "type": "text",
   "description": "Number of GET operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "content": "Number of GET operations on Zookeeper backend by Vault."
  },
  {
   "title": "Vault: Zookeeper GET operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of a GET operation against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_get_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Duration of a GET operation against the ZooKeeper, 90th percentile",
   "type": "text",
   "description": "Duration of a GET operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "content": "Duration of a GET operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile"
  },
  {
   "title": "Vault: ZooKeeper PUT operations count",
   "type": "graph",
   "description": "Number of PUT operations on ZooKeeper by Vault",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_put_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Zookeeper PUT operations count",
   "type": "text",
   "description": "Number of PUT operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "content": "Number of PUT operations on Zookeeper backend by Vault."
  },
  {
   "title": "Vault: Zookeeper PUT operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of a PUT operation against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_put_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Duration of a PUT operation against the ZooKeeper, 90th percentile",
   "type": "text",
   "description": "Duration of a PUT operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Duration of a PUT operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile"
  },
  {
   "title": "Vault: ZooKeeper DELETE operations count",
   "type": "graph",
   "description": "Number of DELETE operations on ZooKeeper by Vault",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_delete_count{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Zookeeper DELETE operations count",
   "type": "text",
   "description": "Number of DELETE operations on Zookeeper backend by Vault.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "content": "Number of DELETE operations on Zookeeper backend by Vault."
  },
  {
   "title": "Vault: Zookeeper DELETE operation duration, 90th percentile",
   "type": "graph",
   "description": "Duration of a DELETE operation against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_zookeeper_delete_90_percentile{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vault: Duration of a DELETE operation against the ZooKeeper, 90th percentile",
   "type": "text",
   "description": "Duration of a DELETE operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "content": "Duration of a DELETE operation (in milliseconds) against the ZooKeeper storage backend, 90th percentile"
  }
 ]
}