{
 "title": "Edge-LB: Pool Server - HAProxy",
 "tags": [ "edge-lb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dcos_cluster_name",
    "label": "DC/OS Cluster",
    "query": "label_values(dcos_cluster_name)"
   },
   { "name": "applicationPath", "label": "Application path", "query": "label_values(applicationPath)" },
   { "name": "poolName", "label": "Pool name", "query": "label_values(poolName)" },
   {
    "name": "poolServer",
    "label": "Pool Server",
    "query": "label_values(dcos_edgelb_haproxy_frontend_bytes_in_total{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\"}, task_name)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(dcos_edgelb_haproxy_frontend_bytes_in_total{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\"}, frontend)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(dcos_edgelb_haproxy_backend_bytes_in_total{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\"}, backend)"
   },
   {
    "name": "backendServer",
    "label": "Backend server",
    "query": "label_values(dcos_edgelb_haproxy_server_bytes_in_total{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\", backend=~\"$backend\"}, server) "
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(dcos_edgelb_haproxy_server_http_responses_total{poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\", backend=~\"$backend\", server=~\"$backendServer\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "Edge-LB dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  { "title": "Basic Backend status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Backends Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(dcos_edgelb_haproxy_backend_up{backend=~\"$backend\", poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\"} == 1) by (poolName)",
     "legendFormat": "Backends Up@{{poolName}}"
    },
    {
     "expr": "count(dcos_edgelb_haproxy_backend_up{backend=~\"$backend\", poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\"} == 0) by (poolName)",
     "legendFormat": "Backends Down@{{poolName}}"
    }
   ]
  },
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Responses by HTTP code",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (code)",
     "legendFormat": "Frontend [{{ code }}]"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (code)",
     "legendFormat": "Backend [{{ code }}]"
    }
   ]
  },
  {
   "title": "Incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "IN Frontend@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "OUT Frontend@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_bytes_in_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "IN Backend@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_bytes_out_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "OUT Backend@{{poolName}}"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_connections_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Frontend@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_connection_errors_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Backend errors@{{poolName}}"
    }
   ]
  },
  {
   "title": "Requests / responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_http_requests_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Requests@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_response_errors_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\" ,task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Response errors@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_request_errors_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Requests errors@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Backend redispatch@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_backend_retry_warnings_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\" ,task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Backend retry@{{poolName}}"
    },
    {
     "expr": "sum(irate(dcos_edgelb_haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", task_name=~\"$poolServer\"}[5m])) by (poolName)",
     "legendFormat": "Request denied@{{poolName}}"
    },
    {
     "expr": "sum(dcos_edgelb_haproxy_backend_current_queue{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\", task_name=~\"$poolServer\"}) by (poolName)",
     "legendFormat": "Backend Queued@{{poolName}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dcos_edgelb_haproxy_frontend_current_sessions{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName)",
     "legendFormat": "Frontend current sessions@{{poolName}}"
    },
    {
     "expr": "sum(dcos_edgelb_haproxy_frontend_current_session_rate{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName)",
     "legendFormat": "Frontend current session rate@{{poolName}}"
    },
    {
     "expr": "sum(dcos_edgelb_haproxy_backend_current_sessions{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName)",
     "legendFormat": "Backend current sessions@{{poolName}}"
    },
    {
     "expr": "sum(dcos_edgelb_haproxy_backend_current_session_rate{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName)",
     "legendFormat": "Backend current session rate@{{poolName}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
       "legendFormat": "IN-{{ frontend }}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(poolName)",
       "legendFormat": "OUT-{{ frontend }}"
      }
     ]
    },
    {
     "title": "Backend - incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_bytes_in_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
       "legendFormat": "IN-{{ backend }}@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_bytes_out_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName)",
       "legendFormat": "OUT-{{ backend }}@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - connection rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_connections_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName,frontend)",
       "legendFormat": "{{ frontend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Backend - connections rate: OK / Error",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_sessions_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend,poolName)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_connection_errors_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend,poolName)",
       "legendFormat": "{{ backend }} Error@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend - number of queued requests not assigned to any server",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_backend_current_queue{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName,backend)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - HTTP requests OK / Error / Denied",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_http_requests_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (frontend,poolName)",
       "legendFormat": "{{ frontend }}@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_request_errors_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (frontend,poolName)",
       "legendFormat": "{{ frontend }} Error@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (frontend,poolName)",
       "legendFormat": "{{ frontend }} Denied@{{poolName}}"
      }
     ]
    },
    {
     "title": "Back - Total of redispatch / error / retry warnings",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by(poolName,backend)",
       "legendFormat": "Redispatch {{ backend }}@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_retry_warnings_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))  by(poolName,backend)",
       "legendFormat": "Retry {{ backend }}@{{poolName}}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_response_errors_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by(poolName,backend)",
       "legendFormat": "Error {{ backend }}@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (poolName,code,frontend)",
       "legendFormat": "[{{ code }}] {{ frontend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Back - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (code,backend,poolName)",
       "legendFormat": "[{{ code }}] {{ backend }}@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend - current number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_frontend_current_sessions{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by(poolName)",
       "legendFormat": "{{ frontend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Backend - current number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_backend_current_sessions{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(poolName,backend)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Frontend - current number of sessions rate per second over last elapsed second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_frontend_current_session_rate{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName,frontend)",
       "legendFormat": "{{ frontend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Backend - current number of sessions rate per second over last elapsed second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_backend_current_session_rate{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by (poolName,backend)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      }
     ]
    },
    {
     "title": "Frontend - maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_haproxy_frontend_max_sessions{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "{{ frontend }}@{{poolName}}:{{task_name}}"
      },
      {
       "expr": "min(dcos_edgelb_haproxy_frontend_limit_sessions{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by(poolName,frontend)",
       "legendFormat": "{{ frontend }} limit@{{poolName}}"
      }
     ]
    },
    {
     "title": "Backend - maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_backend_max_sessions{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName,backend)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      },
      {
       "expr": "min(dcos_edgelb_haproxy_backend_limit_sessions{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName,backend)",
       "legendFormat": "{{ backend }} limit@{{poolName}}"
      }
     ]
    },
    {
     "title": "Frontend - maximum number of sessions rate per second and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_haproxy_frontend_max_session_rate{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "{{ frontend }}@{{poolName}}:{{task_name}}"
      },
      {
       "expr": "min(dcos_edgelb_haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by(poolName,frontend)",
       "legendFormat": "{{ frontend }} limit@{{poolName}}"
      }
     ]
    },
    {
     "title": "Backend - Maximum number of sessions rate per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dcos_edgelb_haproxy_backend_max_session_rate{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}",
       "legendFormat": "{{ backend }}@{{poolName}}:{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend - current health status of the backend",
     "type": "graph",
     "description": "The resulting metric is the ratio of the pool servers that see the backed as up to the total number of pool servers for the given pool.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(dcos_edgelb_haproxy_backend_up{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (backend,poolName)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      },
      {}
     ]
    },
    {
     "title": "Backend - total weight of the servers in the backend",
     "type": "graph",
     "description": "The average weight of the given backend. A pool can have more than 1 pool server, hence the average is calculated across all the pool servers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(dcos_edgelb_haproxy_backend_weight{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (poolName,backend)",
       "legendFormat": "{{ backend }}@{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - incoming / outgoing bytes",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_bytes_in_total{backend=~\"$backend\",server=~\"$backendServer\", poolName =~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend, server)",
       "legendFormat": "[IN] {{ backend }} / {{ server }}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_bytes_out_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend, server)",
       "legendFormat": "[OUT] {{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - connections rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_sessions_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by (backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - number of queued requests assigned to this server",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_server_current_queue{backend=~\"$backend\",server=~\"$$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - maximum observed number of queued requests assigned to this server",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_server_max_queue{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}) by (backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - total of HTTP responses OK",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend,server)",
       "legendFormat": "{{ backend}} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - retry / error / redispatch warnings",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_retry_warnings_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m])) by (backend,server)",
       "legendFormat": "[retry] {{ backend }} / {{ server }}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_redispatch_warnings_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(backend,server)",
       "legendFormat": "[redispatch] {{ backend }} / {{ server }}"
      },
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_response_errors_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(backend,server)",
       "legendFormat": "[error] {{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - HTTP responses rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$backendServer\",code=~\"$code\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(backend,server,code)",
       "legendFormat": "[{{ code }}] {{ backend }}/{{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - current number of active sessions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_server_current_sessions{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - sessions rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_server_current_session_rate{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By Server Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - total downtime",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_server_downtime_seconds_total{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - failed health checks",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(dcos_edgelb_haproxy_server_check_failures_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - connection errors",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_server_connection_errors_total{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - health check duration",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "max(dcos_edgelb_haproxy_server_check_duration_milliseconds{backend=~\"$backend\",server=~\"$backendServer\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - server health",
     "type": "graph",
     "description": "The sever health is an average of the health metrics across the given pool, application path, and dc/os cluster.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(dcos_edgelb_haproxy_server_up{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server)",
       "legendFormat": "{{ backend }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - weight of the server",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(dcos_edgelb_haproxy_server_weight{backend=~\"$backend\",poolName=~\"$poolName\", applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(backend,server,poolName)",
       "legendFormat": "{{ backend }} / {{ server }} @ {{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of errors while parsing CSV",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dcos_edgelb_haproxy_exporter_csv_parse_failures{poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"})by(poolName)",
       "legendFormat": "{{poolName}}"
      }
     ]
    },
    {
     "title": "Scrape rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(dcos_edgelb_haproxy_exporter_total_scrapes{poolName=~\"$poolName\",applicationPath=~\"$applicationPath\",dcos_cluster_name=~\"$dcos_cluster_name\",task_name=~\"$poolServer\"}[5m]))by(poolName)",
       "legendFormat": "{{poolName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Licensing information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 102 },
     "content": "##### Copyright (C) 2019 Mesosphere, Inc.\n\nBased on grafana dashbords by Ricardo Fraile, Copyright (C) 2019 Ricardo Fraile\nSource code is availabe at https://github.com/dcos/grafana-dashboards\n\nThis dashboard is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.  https://opensource.org/licenses/LGPL-3.0"
    }
   ]
  }
 ]
}