{
 "title": "Kubernetes - etcd Cluster",
 "description": "etcd sample Grafana dashboard with Prometheus",
 "tags": [
  "kubernetes",
  "mke"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster Name", "query": "label_values(cluster_name)" }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{cluster_name=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{cluster_name=\"$cluster_name\",grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{cluster_name=\"$cluster_name\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{cluster_name=\"$cluster_name\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster_name=\"$cluster_name\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{cluster_name=\"$cluster_name\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{cluster_name=\"$cluster_name\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster_name=\"$cluster_name\"}",
     "legendFormat": "{{instance}} DB Size"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{cluster_name=\"$cluster_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster_name=\"$cluster_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{cluster_name=\"$cluster_name\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{cluster_name=\"$cluster_name\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{cluster_name=\"$cluster_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{cluster_name=\"$cluster_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{cluster_name=\"$cluster_name\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{cluster_name=\"$cluster_name\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{cluster_name=\"$cluster_name\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{cluster_name=\"$cluster_name\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{cluster_name=\"$cluster_name\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  }
 ]
}