{
 "title": "Kubernetes: kc01 Cluster Health",
 "tags": [
  "kubernetes",
  "mke"
 ],
 "time": { "from": "now-15m", "to": "now-1m" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate_interval", "label": "Rate Interval", "query": "10s,30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "etcd Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current number of etcd instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{cluster_name=\"k8s-clusterskc01\",exported_instance=~\"etcd.*\"})",
     "legendFormat": "Total number of etcd instances"
    }
   ]
  },
  {
   "title": "Number of etcd instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{cluster_name=\"k8s-clusterskc01\",exported_instance=~\"etcd.*\"})",
     "legendFormat": "Number of etcd instances"
    }
   ]
  },
  {
   "title": "CPU Usage etcd instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{service_name=\"k8s-clusters/kc01\",executor_name=\"etcd\"}",
     "legendFormat": "CPU Limit ({{executor_name}} {{container_id}})"
    },
    {
     "expr": "rate(cpus_system_time_secs{service_name=\"k8s-clusters/kc01\",executor_name=\"etcd\"}[$rate_interval]) + rate(cpus_user_time_secs{service_name=\"k8s-clusters/kc01\",executor_name=\"etcd\"}[$rate_interval])",
     "legendFormat": "CPU Usage ({{executor_name}} {{container_id}})"
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Current number of Apiservers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster_name=\"k8s-clusterskc01\",exported_instance=~\"apiserver-kube-control-plane.*\"})"
    }
   ]
  },
  {
   "title": "Number of Apiservers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"apiserver.*\"})",
     "legendFormat": "Total number of Apiservers"
    }
   ]
  },
  {
   "title": "CPU Usage Control Plane",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{service_name=\"k8s-clusters/kc01\",executor_name=\"kube-control-plane\"}",
     "legendFormat": "CPU Limit ({{executor_name}} {{container_id}})"
    },
    {
     "expr": "rate(cpus_system_time_secs{service_name=\"k8s-clusters/kc01\",executor_name=\"kube-control-plane\"}[$rate_interval]) + rate(cpus_user_time_secs{service_name=\"k8s-clusters/kc01\",executor_name=\"kube-control-plane\"}[$rate_interval])",
     "legendFormat": "CPU Usage ({{executor_name}} {{container_id}})"
    }
   ]
  },
  {
   "title": "Current number of Controller Managers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"controller-manager-kube-control-plane.*\"})"
    }
   ]
  },
  {
   "title": "Number of Controller Managers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"controller-manager.*\"})",
     "legendFormat": "Total number of Controller Managers"
    }
   ]
  },
  {
   "title": "Current number of Schedulers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"scheduler-kube-control-plane-.*\"})"
    }
   ]
  },
  {
   "title": "Number of Schedulers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"scheduler.*\"})",
     "legendFormat": "Total number os Schedulers"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Current number of Private Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{cluster_name=\"k8s-clusterskc01\",exported_instance=~\"kube-node-[0-9]+-.*\"})"
    }
   ]
  },
  {
   "title": "Number of Private Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kubelet_node_name{cluster_name=~\"k8s-clusterskc01\",exported_instance=~\"kube-node-[0-9]+.*\"})",
     "legendFormat": "Total number of Private Nodes"
    }
   ]
  },
  {
   "title": "CPU Usage Private nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpus_limit{service_name=\"k8s-clusters/kc01\",executor_name=\"kube-node\"}",
     "legendFormat": "CPU Limit ({{executor_name}} {{container_id}})"
    },
    {
     "expr": "rate(cpus_system_time_secs{service_name=\"k8s-clusters/kc01\",executor_name=\"kube-node\"}[$rate_interval]) + rate(cpus_user_time_secs{service_name=~\"k8s-clusters/kc01\",executor_name=\"kube-node\"}[$rate_interval])",
     "legendFormat": "CPU Usage ({{executor_name}} {{container_id}})"
    }
   ]
  },
  { "title": "Calico", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Current number of Calico nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(felix_host{cluster_name=\"k8s-clusterskc01\"})",
     "legendFormat": "Current number of Calico nodes"
    }
   ]
  },
  {
   "title": "Number of Calico nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(felix_host{cluster_name=\"k8s-clusterskc01\"})",
     "legendFormat": "Number of Calico nodes"
    }
   ]
  },
  {
   "title": "Update Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(felix_int_dataplane_failures{cluster_name=\"k8s-clusterskc01\"}[$rate_interval]))",
     "legendFormat": "Total update failures"
    }
   ]
  },
  {
   "title": "Update Apply Duration p99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(felix_int_dataplane_apply_time_seconds{cluster_name=\"k8s-clusterskc01\",quantile=\"0.99\"}[$rate_interval])",
     "legendFormat": "{{kubernetes_node_name}}"
    }
   ]
  }
 ]
}