{
 "title": "Jenkins: Jobs MWT19",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jenkins provision to ready time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_ready_p99)"
    },
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_ready_p50)"
    }
   ]
  },
  {
   "title": "Job Queuing Duration p99, p50, min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_jenkins_job_queuing_duration_p99)"
    },
    {
     "expr": "max(jenkinsstatsd_jenkins_job_queuing_duration_p50)"
    },
    {
     "expr": "max(jenkinsstatsd_jenkins_job_queuing_duration_p95)"
    },
    {
     "expr": "min(jenkinsstatsd_jenkins_job_queuing_duration_min)"
    },
    {
     "expr": "avg(jenkinsstatsd_jenkins_job_queuing_duration_mean)"
    }
   ]
  },
  {
   "title": "Jenkins Job buildable duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jenkinsstatsd_jenkins_job_buildable_duration_mean)"
    },
    {
     "expr": "max(jenkinsstatsd_jenkins_job_buildable_duration_p99)"
    }
   ]
  },
  {
   "title": "Executors Total (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Executors" }
   ],
   "targets": [
    {
     "expr": "sum(jenkinsstatsd_jenkins_executor_count_value)"
    }
   ]
  },
  {
   "title": "Jenkins Provision time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_mesos_max)"
    },
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_mesos_p50)"
    },
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_mesos_p99)"
    }
   ]
  },
  {
   "title": "Number of Jenkins Masters",
   "type": "graph",
   "description": "# of Jenkins masters currently running in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(jenkinsstatsd_jenkins_queue_size_value)"
    }
   ]
  },
  {
   "title": "Jenkins Scheduler max wait time (total time scheduler waits for offer)",
   "type": "graph",
   "description": "p50, p99 and p95 breakdown",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_scheduler_p99)"
    },
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_scheduler_p95)"
    },
    {
     "expr": "max(jenkinsstatsd_mesos_cloud_mesos_provision_scheduler_p50)"
    },
    {
     "expr": "min(jenkinsstatsd_mesos_cloud_mesos_provision_scheduler_min)"
    },
    {
     "expr": "avg(jenkinsstatsd_mesos_cloud_mesos_provision_ready_mean)"
    }
   ]
  },
  {
   "title": "Job Queuing Duration - Job Blocked Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg(jenkinsstatsd_jenkins_job_queuing_duration_mean) - avg(jenkinsstatsd_jenkins_job_blocked_duration_mean))"
    },
    {
     "expr": "avg(jenkinsstatsd_jenkins_job_waiting_duration_mean)"
    },
    {
     "expr": "avg(jenkinsstatsd_jenkins_job_building_duration_mean)/3600"
    }
   ]
  }
 ]
}