{
 "title": "CockroachDB: Details SQL",
 "tags": [
  "dc/os",
  "detail",
  "cockroachdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "DC/OS Master Nodes",
    "query": "label_values(sys_uptime{dcos_component_name=\"CockroachDB\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "SQL Connections: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sql_conns{dcos_component_name=\"CockroachDB\",host=~\"$node\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Connections: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sql_conns{dcos_component_name=\"CockroachDB\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(sql_bytesout{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Bytes in/out: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(sql_bytesin{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}} - in"
    },
    {
     "expr": "rate(sql_bytesout{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}} - out"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(sql_select_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_insert_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_update_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_delete_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "abort"
    },
    {
     "expr": "sum(rate(sql_txn_rollback_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(sql_txn_begin_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_txn_commit_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_txn_abort_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]) + rate(sql_txn_rollback_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Schema changes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "DDL"
    }
   ]
  },
  {
   "title": "Schema Changes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(sql_ddl_count{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(sql_exec_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 95th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(sql_exec_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_exec_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 99th Percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_exec_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}