{
 "title": "CockroachDB: Details Storage",
 "tags": [
  "dc/os",
  "detail",
  "cockroachdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{dcos_component_name=\"CockroachDB\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Storage capacity: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Disk Space"
    },
    {
     "expr": "sum(sum(capacity_available{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Available Capacity "
    },
    {
     "expr": "sum(sum(capacity_used{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Used Capacity "
    },
    {
     "expr": "sum(sum(capacity_reserved{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Reserved Capacity "
    }
   ]
  },
  {
   "title": "Capacity Used: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum(capacity_used{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host) / sum(capacity_available{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Percentage of storage utilization: All",
   "type": "graph",
   "description": "Percentage of storage utilization w.r.t. capacity of the total storage available to CockroachDB",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(capacity_used{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) / sum(capacity_available{dcos_component_name=\"CockroachDB\"})) * 100",
     "legendFormat": "{{Storage utilization}}"
    }
   ]
  },
  {
   "title": "Percentage of storage utilization per node: All",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "(sum(capacity_used{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host) / sum(capacity_available{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(sum(sysbytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Internal"
    }
   ]
  },
  {
   "title": "Live Bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(livebytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "avg(rocksdb_read_amplification{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rocksdb_num_sstables{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} / (rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} + rocksdb_block_cache_misses{dcos_component_name=\"CockroachDB\",host=~\"$node\"})",
     "legendFormat": "{{host}}:{{store}}"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} / (rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} + rocksdb_block_cache_misses{dcos_component_name=\"CockroachDB\",host=~\"$node\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Raft command commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(raft_process_commandcommit_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Raft command commit latency: 99th percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(raft_process_commandcommit_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Raft log commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(raft_process_logcommit_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Raft log commit latency: 99th percentile",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(raft_process_logcommit_latency_bucket{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "File Descriptors: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "File descriptor usage: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(sys_fd_open{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host) / sum(sys_fd_softlimit{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}