{
 "title": "CockroachDB: Details Replicas",
 "tags": [
  "dc/os",
  "detail",
  "cockroachdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{dcos_component_name=\"CockroachDB\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ranges: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft leaders not lease holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "Ranges: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(ranges{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}} - ranges"
    },
    {
     "expr": "sum(ranges_unavailable{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}} - unavailable"
    }
   ]
  },
  {
   "title": "Raft Log: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raftlog_behind{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft log behind"
    },
    {
     "expr": "sum(sum(rate(raftlog_truncated{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "raft log truncated"
    },
    {
     "expr": "sum(sum(raftlog_selfbehind{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft log self behind"
    }
   ]
  },
  {
   "title": "Raft Log Behind: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(raftlog_behind{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Quiescent"
    },
    {
     "expr": "sum(sum(replicas{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host) - sum(replicas_quiescent{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Quiescent Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(replicas_quiescent{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Replicas per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(replicas{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logical bytes per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(keybytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host) + sum(valbytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Live bytes: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(livebytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Keys written per second per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Keys written per second: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "splits"
    },
    {
     "expr": "sum(sum(rate(range_adds{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "removes"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(range_splits{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host) + sum(rate(range_adds{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host) + sum(rate(range_removes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_snapshots_generated{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_normal_applied{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "Normal-applied"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_preemptive_applied{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host))",
     "legendFormat": "Preemptive-applied"
    },
    {
     "expr": "sum(replicas_reserved{dcos_component_name=\"CockroachDB\",host=~\"$node\"})",
     "legendFormat": "Reservations"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host)",
     "legendFormat": "{{host}} - generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host) + sum(rate(range_snapshots_preemptive_applied{dcos_component_name=\"CockroachDB\",host=~\"$node\"}[$rate_interval])) by (host)",
     "legendFormat": "{{host}} - applied"
    }
   ]
  }
 ]
}