{
 "title": "CockroachDB: Summary",
 "tags": [
  "dc/os",
  "summary",
  "cockroachdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{dcos_component_name=\"CockroachDB\"},host)"
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Live Node Count: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(up{dcos_component_name=\"CockroachDB\",instance=~\"$node\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{dcos_component_name=\"CockroachDB\",instance=~\"$node\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{dcos_component_name=\"CockroachDB\",instance=~\"$node\"})",
     "legendFormat": "Number of live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "CockroachDB Live Node Count",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "content": "Number of live instances in the CockroachDB cluster determined via the CockroachDB internal heartbeat mechanism. Since DC/OS deploys one CockroachDB instance per DC/OS master node this is number must always match the number of expected master nodes in the DC/OS cluster."
  },
  {
   "title": "Uptime: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sys_uptime{dcos_component_name=\"CockroachDB\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CockroachDB Uptime",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "content": "Uptime reported by each CockroachDB node process. This indicates for how long each CockroachDB node process has been running since its last launch. It gives insight into unavailability due to downtime and unexpected restarts by the DC/OS bootstrap mechanism."
  },
  {
   "title": "Mean RPC Clock Offset: $node",
   "type": "graph",
   "description": "Mean clock offset with other nodes as measured by cockroach.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "clock_offset_meannanos{dcos_component_name=\"CockroachDB\", host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CockroachDB Mean RPC Clock Offset",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "content": "Mean RPC Clock Offset measures the clock drift between CockroachDB nodes. CockroachDB relies on clock synchronization to guarantee serializability. When a node detects that its clock is out of synch with at least half of the other nodes in the cluster by 80% of the maximum offset allowed (500ms), it spontaneously shuts down."
  },
  {
   "title": "Storage capacity: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Capacity"
    },
    {
     "expr": "sum(sum(capacity_available{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(sum(capacity_used{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity_reserved{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "CockroachDB Storage Capacity",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "content": "Amount of total storage capacity in Gigabytes versus amount of storage currently in use."
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(sum(sysbytes{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "Internal"
    }
   ]
  },
  {
   "title": "CockroachDB Bytes",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "content": "Number of bytes of system data stored for CockroachDB internal purposes versus number of bytes of live data from DC/OS."
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} / (rocksdb_block_cache_hits{dcos_component_name=\"CockroachDB\",host=~\"$node\"} + rocksdb_block_cache_misses{dcos_component_name=\"CockroachDB\",host=~\"$node\"})",
     "legendFormat": "{{host}}:{{store}}"
    }
   ]
  },
  {
   "title": "CockroachDB RocksDB cache hit rate",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "content": "Cache hit rate of the underlying key-value store RocksDB per CockrochDB node. The cache hit rate is calculated as the number of Cache hits divided by the number of Cache accesses."
  },
  {
   "title": "Ranges: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "raft leaders not lease holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{dcos_component_name=\"CockroachDB\",host=~\"$node\"}) by (host))",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "CockroachDB Ranges",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "content": "Number of CockroachDB ranges in the cluster. In order to guarantee that no data is lost, before doing an upgrade of a DC/OS master node the number of underreplicated ranges must be zero."
  }
 ]
}